### ISSUE TITLE
PURLs aren't compliant with PURL specs

### ISSUE THREAD

**Issue by mrizzi** [trustification/trustify#1004]
PURLs retrieved from Trustify aren't compliant with specs for PURL.

PURL specs has the `scheme:type/namespace/name@version?qualifiers#subpath` format, ref. https://github.com/package-url/purl-spec?tab=readme-ov-file#purl

Trustify retrieved PURLs have a `//` between `scheme:` and `type`, e.g. `pkg://maven/org.apache/log4j@1.2.3?jdk=11` instead of `pkg:maven/org.apache/log4j@1.2.3?jdk=11`.

As an example, in [`package_version`](https://github.com/trustification/trustify/blob/ed72d871cd9a9d2afe6ce30380d0bbd5edf7b497/modules/fundamental/src/purl/service/test.rs#L237) test:

- the input PURL is [`pkg:maven/org.apache/log4j@1.2.3?jdk=11`](https://github.com/trustification/trustify/blob/ed72d871cd9a9d2afe6ce30380d0bbd5edf7b497/modules/fundamental/src/purl/service/test.rs#L251)
- but then the one in the test assertion is a different one, i.e. [`pkg://maven/org.apache/log4j@1.2.3?jdk=11`](https://github.com/trustification/trustify/blob/ed72d871cd9a9d2afe6ce30380d0bbd5edf7b497/modules/fundamental/src/purl/service/test.rs#L305)

**Comment by PhilipCattanach** [comment]
@JimFuller-RedHat - This seems like a fundamental problem to me. And to be honest a bit worrying. Can you investigate this please?

**Comment by JimFuller-RedHat** [comment]
The db just emulates how we serialise pURL elsewhere in the code - this is a semantic question - of which I do not know the history/context on - will catch up with @ctron

**Comment by JimFuller-RedHat** [comment]
adding:

* @ctron had noted we didn't support #paths 
* @bobmcwhirter  introduced pkg:// notation which can be fixed

considering it sounds like no previous context applies - should be an easy fix (with migration)
