### ISSUE TITLE
Sort SBOMs and Advisories by "ingestion time"

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#1077]
This issue is a follow up of https://github.com/trustification/trustify/issues/952

- The use case is the Dashboard where we render the last 10 SBOMs ingested and on the right side we render the date in which the last advisory was ingested.
  - Currently what I am doing is to fetch `GET /api/v1/sbom/`, sort it by `published` and in this way I have the 10 SBOMs the dashboard will render. But what we need it to be able to sort SBOMs by "when the date in which the file was imported into the system". Same for Advisories

@jcrossley3 tagging you here as you implemented nicely the Dashboard use case, and you are familiar with the use case.

**Comment by jcrossley3** [comment]
@carlosthe19916 you should now be able to call `/api/v1/sbom?sort=ingested%3Adesc&limit=10` to get the 10 most recently ingested SBOM's.

I didn't realize you needed it for advisories, too, though. PR forthcoming.
