### ISSUE TITLE
AuthN/AuthZ

### ISSUE THREAD

**Issue by bobmcwhirter** [trustification/trustify#11]
What's needed for authentication?

Do we *need* a KeyCloak? Can we defer (for dev at least?) to GH OAuth or similar?

**Comment by ctron** [comment]
To my understanding we might be able to use https://github.com/HeroicKatora/oxide-auth … kind of like SQlite for OIDC.

**Comment by jcrossley3** [comment]
Can we close this?

**Comment by ctron** [comment]
I think the Authentication part is solved. The authorization part is there, but leaves a lot of room for improvement. That could be tracked in a more focused issued though.

**Comment by ctron** [comment]
Tracking issue for authorization: https://github.com/trustification/trustify/issues/554
