### ISSUE TITLE
Upload Advisory should only require the file, everything else should be determined by the server

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#144]
## Current status:

https://github.com/trustification/trustify/blob/52b2cc9dfaa325ffcfdaee30e38371e444443b1f/modules/ingestor/src/endpoints/advisory.rs#L14C1-L26C23

```rust
#[utoipa::path(
    tag = "ingestor",
    request_body = Vec <u8>,
    params(
        ("format" = String, Query, description = "Format of the submitted advisory document (`csaf`, `osv`, ...)"),
        ("location" = String, Query, description = "Source the document came from"),
    ),
    responses(
        (status = 201, description = "Upload a file"),
        (status = 400, description = "The file could not be parsed as an advisory"),
    )
)]
#[post("/advisories")]
```

## Problem
- Format & location query parameters are required to upload a file

It means that the UI can not just take a file and upload it. It requires the user fill a form to specify the `format` of the file he is uploading, which is in my opinion prone to error and not user friendly. Imagine yourself uploading a file using CURL but you can not just take a file and upload it, but you have to determine which is the format of it. The problem is for humans, probably not for other apps

## Proposed solution
- The FILE should be the only required thing, everything else should be determined by the server
  - For the `location` query parameter: Technically the UI can be deployed in a different domain than the Backend, There can be multiple UI domains pointing to the same backend. `location` should be determined in the backend side as the relative path of the rest endpoint used e.g. `/advisories` 
  - for the `format` query parameter. There are JSON Schemas for each of the formats supported. Why we can just use the schemas to validate to which one the file belongs to? e.g. User uploads a file => the server compares the file to each of the supported json schemas => the format is determined by the server as the schema to which the file matches. That should be it. The JSON Schemas are
  

- CSAF Schema: https://github.com/oasis-tcs/csaf/blob/master/csaf_2.0/json_schema/csaf_json_schema.json
- OSV Schema https://github.com/ossf/osv-schema/blob/main/validation/schema.json
- CVE
Schema: https://github.com/CVEProject/cve-schema/blob/master/schema/v5.0/CVE_JSON_5.0_schema.json

**Comment by ctron** [comment]
In my opinion the meaning of `location` isn't defined clearly enough at the moment. To my understanding it has nothing do to with any of our locations, but the location the document originated from. e.g. when scooping up Red Hat data via CSAF, the base URL where the document was found.

When manually uploading through the frontend, that information could either be `"frontend"`, or `<the user uploading it>`, or actually some source location the user knows about and would need to enter it.

**Comment by carlosthe19916** [comment]
I see... so, may I suggest to relax the `location` parameter so we make it optional?. If the user does no specify we can set a default value like `location=rest-api`. I still think the file should be the only mandatory thing anyone should send to the server

**Comment by ctron** [comment]
> If the user does no specify we can set a default value like `location=rest-api`.

Yup. I would leave that handling to the server side. A fixed string, the subject from the OIDC token, … but it shouldn't be a concern of the user, unless the user wants to attach that information.

**Comment by bobmcwhirter** [comment]
I think `location` should simply go away. SHA should be sufficient to identify something.

**Comment by bobmcwhirter** [comment]
If we want to track *who* uploaded a document, that should be a join to a not-yet-existing `User` table.

**Comment by bobmcwhirter** [comment]
I guess ultimately, do we care? Or do we care that "we have seen some VEX, about some Product, signed by Red Hat"?

**Comment by bobmcwhirter** [comment]
That being said, if an importer needs to track "locations" it has already grabbed, for its own logistics, that's fine.

**Comment by carlosthe19916** [comment]
The issue pointed out 2 things that I suggested to be removed `location` and `format`. It seems we are kind of in the same page in regards to `location`... nobody mentioned `format`, I'll assume that it will be removed from the query parameters and not be required right xD?

**Comment by bobmcwhirter** [comment]
I think we'll need some designation of format, so that the system knows what format to attempt parsing/ingesting of a given document type.
