### ISSUE TITLE
Importer POST /api/v1/importer/{name} should be /api/v1/importer/

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#151]
At the moment we are using a Path Parameter to define the `name` of an importer. Although it works, we should follow common practices when we define our endpoints, here is a basic example:

- `GET /personas`: List of personas
- `POST /personas`: Create a single persona. Any info required goes in the body of the POST request
- `GET /personas/{id}`: get a single persona
- `PUT /personas/{id}`: update a persona
- `DELETE /personas/{id}`: delete a persona

So `/api/v1/importer/{name}` should be changed by `/api/v1/importer/` and the name should be defined in the body of the request.

**Comment by ctron** [comment]
> So `/api/v1/importer/{name}` should be changed by `/api/v1/importer/` and the name should be defined in the body of the request.

I fail to see the benefit in that … it would just mean creating an additional struct.

**Comment by carlosthe19916** [comment]
> > So `/api/v1/importer/{name}` should be changed by `/api/v1/importer/` and the name should be defined in the body of the request.
> 
> I fail to see the benefit in that … it would just mean creating an additional struct.

The modeling of the APIs should not be driven by the constraints of a programming language. The REST APIs practices/modeling/patterns are there regardless of in which programming language a server is written in.

**Comment by carlosthe19916** [comment]
You 

> Correct, but it should make sense. And I still fail to see the benefit of breaking that naming pattern. Maybe you can explain it.

I would reply with a question: is the argument for not doing it: `it would just mean creating an additional struct.`? Is that the way we are designing our application?

If we think the idea described in this ticket is a bad idea or not convenient then fine. I'm just bringing ideas, I don't want to impose them. Feel free to close this issue.

**Comment by ctron** [comment]
I would like to understand it. You say "Although it works" … so it does work, so why change it? Why should the name of the resource be part of the body? Why create a difference (also for the user) in the payload between creating vs updating a resource? I don't see the benefit, so maybe it is worth explaining where the benefit is?

If there is a benefit, then maybe it's worth changing what already works.

**Comment by jcrossley3** [comment]
I don't have a strong opinion on this. I like the consistency of the path for all the CRUD operations, but I bristle at using a plural:

> * `GET /personas`: List of personas
> * `POST /personas`: Create a single persona. Any info required goes in the body of the POST request
> * `GET /personas/{id}`: get a single persona
> * `PUT /personas/{id}`: update a persona
> * `DELETE /personas/{id}`: delete a persona

I'm less offended by GET'ting a list of `/persona` than I am POST'ing a single `/personas` :smile: 

I prefer:

* `GET /persona`: List of personas
* `POST /persona`: Create a single persona. Any info required goes in the body of the POST request
* `GET /persona/{id}`: get a single persona
* `PUT /persona/{id}`: update a persona
* `DELETE /persona/{id}`: delete a persona

Is the plural path common in REST land?

**Comment by carlosthe19916** [comment]
- @jcrossley3 using singular instead of plural is fine.
- The original idea of the gh issue was about using "name" in the POST request 

But ok. As it works, let's leave it as it is.
