### ISSUE TITLE
Documents having their own document ID need to be grouped

### ISSUE THREAD

**Issue by ctron** [trustification/trustify#158]
For documents which have their own document ID and which can change over time (like CSAF documents), there must be a way to get that latest document by its document ID. When searching, only the latest document must be searched and returned (unless we want an additional API to search through the history).

**Comment by jcrossley3** [comment]
Still relevant?

**Comment by ctron** [comment]
No this was actually fixed by https://github.com/trustification/trustify/pull/845 for CSAF docs. And for SBOMs, we need a better definition of what "latest" means.
