### ISSUE TITLE
Bring over Infrastructure

### ISSUE THREAD

**Issue by bobmcwhirter** [trustification/trustify#16]

**Comment by ctron** [comment]
I tend to extract it into a dedicated module/project when I do it the third time. Drogue was one, Trustification was second, this would be the third. I would want to keep it simpler then "Bazaar", but still: had we extracted that properly "back then", we would not just need to add another crate and consume it.

**Comment by bobmcwhirter** [comment]
Wouldja consider this done?

**Comment by ctron** [comment]
Since #70 is merged, yes!
