### ISSUE TITLE
Hash more than just SHA256

### ISSUE THREAD

**Issue by bobmcwhirter** [trustification/trustify#161]
Some day SHA256 will be broken maybe, so let's go ahead and hash SHA384 and whatever else seems sensible.

**Comment by bobmcwhirter** [comment]
@helio-frota if you're interested, you could add SHA384 here:

https://github.com/trustification/trustify/blob/main/modules/ingestor/src/service/hashing.rs

**Comment by crsche** [comment]
Hey @bobmcwhirter, could I give this issue a shot. I'm a bit new to group contribution, but I'll see what I can do.

**Comment by bobmcwhirter** [comment]
Right on, thanks! Should be fairly straight-forward (famous last words). Just fork, branch, submit a PR and I'll be glad to review it.

**Comment by bobmcwhirter** [comment]
Closed implemented by #182
