### ISSUE TITLE
PaginatedResults<T> support for OpenAPI schema bodies

### ISSUE THREAD

**Issue by bobmcwhirter** [trustification/trustify#162]
Yeah?

**Comment by ctron** [comment]
For sure, but there are some technical limitations.

**Comment by carlosthe19916** [comment]
I do see the schemas in paginated results. I am closing this issue as I think it has been covered already. If we think it was not we can reopen it later on

![image](https://github.com/trustification/trustify/assets/2582866/1fbef143-644f-4d03-9f32-83b7468a4f55)
