### ISSUE TITLE
Importer[period] should be a number and not a string

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#164]
### Current status

- From the README.md file the `period` can be written as `60s` to express "60" seconds.
```
http POST localhost:8080/api/v1/importer/redhat-csaf csaf[period]=60s
```

- The list of importers at `http://localhost:8080/api/v1/importer` can return `period=1m`
```json
[
    {
        "name": "redhat-csaf",
        "configuration": {
            "csaf": {
                "disabled": false,
                "period": "1m",
                "source": "https://redhat.com/.well-known/csaf/provider-metadata.json",
                "v3Signatures": false
            }
        },
        "state": "waiting",
        "lastChange": "2024-04-16T06:32:13.941898Z",
        "lastRun": "2024-04-16T06:32:11.428871Z",
        "lastError": "Visitor error: Invalid signature: Invalid key: \"Subkey of 77E79ABE93673533ED09EBE2DCE3823597F5EAC4 not bound: No binding signature at time 2024-04-16T04:20:22Z\""
    }
]
```

### Problem
There is no unique way of expressing `period`.
`period` should be a number (seconds, milliseconds or whatever else) as an Input and Output. The Clients (e.g. UI) and Backend should then translate the number to the format of their preference.

**Comment by ctron** [comment]
Things like duration should *always* have a unit. There are so many cases where a missing unit leads to unexpected results.

**Comment by carlosthe19916** [comment]
I agree, duration should always have a measurement unit
- I was suggesting to have one and only one unit which would be for instance milliseconds (a number and not a string).
- If having multiple measurement units is better, then can we document which are the units supported?

**Comment by ctron** [comment]
Right however. that doesn't carry that information in the value: `timeout: 1000` … what unit is it? `timeout: 1000s` is pretty clear.

Bugs this his have happened so many times. Specifically stating the unit solves this.

**Comment by carlosthe19916** [comment]
No problem. Can we document which are the supported suffixes to refer to measure units?

**Comment by ctron** [comment]
```
    nsec, ns -- nanoseconds
    usec, us -- microseconds
    msec, ms -- milliseconds
    seconds, second, sec, s
    minutes, minute, min, m
    hours, hour, hr, h
    days, day, d
    weeks, week, w
    months, month, M -- defined as 30.44 days
    years, year, y -- defined as 365.25 days
```

**Comment by carlosthe19916** [comment]
I'm going to close this PR.
- On input data: the REST apis should accept any of the formats mentioned above.
- On output data: I expect the server to be predictable and consistent when using formats. I expect the output to use any of the units `s,m,h,d,w,M,y`. So if period="50 seconds" then the server should always return `50s` and never `50sec` nor `50seconds`.
