### ISSUE TITLE
Remove unused things

### ISSUE THREAD

**Issue by jcrossley3** [trustification/trustify#17]
https://github.com/trustification/trustify/blob/8584c44d8fe9b2f0a1dfcf140601f1c9b22e795d/backend/api/src/lib.rs#L1

Remove these `allow`'s and resolve all the warnings that result from doing so.

**Comment by bobmcwhirter** [comment]
Inception yes. 

Unused? Not yet.

**Comment by jcrossley3** [comment]
> Unused? Not yet.

Why? When?

**Comment by bobmcwhirter** [comment]
Presumably some unused things are just waiting to be hooked up to an actix endpoint and then ... voila! They're used.

**Comment by jcrossley3** [comment]
I was mostly referring to unused imports, of which there are a crap-ton.

**Comment by bobmcwhirter** [comment]
Ah. Complete fair. Yes.

**Comment by helio-frota** [comment]
real feedback?
I started doing this yesterday, and then I noticed that I was deleting a lot of lines.... and I started to be afraid of deleting a lot of things :smiley:
