### ISSUE TITLE
Determine if PM-Mode retains the DB across executions

### ISSUE THREAD

**Issue by bobmcwhirter** [trustification/trustify#171]
In theory, $PWD/.trustify/... should be retained across runs and not blow away the DB each time by default.

**Comment by jcrossley3** [comment]
Turns out there's a `Settings::data_dir` field we need to set to get the desired behavior.  There's a difference between the `installation_dir` and the `data_dir`. The latter is created anew beneath `/tmp` every single time, so the data effectively disappears each time.
