### ISSUE TITLE
Make db::DbStrategy go away

### ISSUE THREAD

**Issue by bobmcwhirter** [trustification/trustify#173]
In reality, with the exception of `for_test(...)` we don't use `db::DbStrategy::Managed(Arc<...>)`, while we *do* use `config::DbStrategy::Managed` but ultimately manage it from the `trustd` wrapper around the DB. The Db we construct and give to Graph is `External` from its POV, which makes complete sense.

I suspect we should rework the `for_test(...)` logic to be more test-fixure-y, and less ingrained in Db/Graph logic.

**Comment by jcrossley3** [comment]
Fixed by #174
