### ISSUE TITLE
Sort out how to embedded-postgresql with some extensions

### ISSUE THREAD

**Issue by bobmcwhirter** [trustification/trustify#186]
For PM mode, we're enjoying the embedded postgres.

I'd like us to be able to use the Trusted Lang Extension and Apache AGE perhaps.

Can we somehow do the embedded route, but with baked-in extensions? Dunno!

**Comment by jcrossley3** [comment]
upstream issue: https://github.com/theseus-rs/postgresql-embedded/issues/47

**Comment by JimFuller-RedHat** [comment]
I believe the spirit of this has been addressed (and we are able to load extensions
