### ISSUE TITLE
Don't spam CI reports

### ISSUE THREAD

**Issue by ctron** [trustification/trustify#19]
I find the warnings spamming the CI reports massively annoying and distracting.

My expectation would be that if there warnings like that, a PR won't get merged before they are resolved. Or, we disable them as we don't seem to care.

Right now, reviewing a PR and getting dozens of unrelated warnings is not helping.

**Comment by jcrossley3** [comment]
Man, they really bother me, too! Pedantry FTW!

**Comment by ctron** [comment]
Closed by #28
