### ISSUE TITLE
Un-ignore tests failing due to inaccessible "$libdir/plpgsql" file

### ISSUE THREAD

**Issue by jcrossley3** [trustification/trustify#202]
After converting over 40 unit tests to get their database instance from a `test_context`, exactly two of those tests fail consistently with this error:
```
Error: Query Error: error returned from database: could not access file "$libdir/plpgsql": No such file or directory

Caused by:
    0: error returned from database: could not access file "$libdir/plpgsql": No such file or directory
    1: error returned from database: could not access file "$libdir/plpgsql": No such file or directory
    2: could not access file "$libdir/plpgsql": No such file or directory
```
Those tests are [sbom_vulnerabilities](https://github.com/trustification/trustify/blob/9e274df6fe9e70eed01c05821dc03ada50d5ba5e/modules/ingestor/src/graph/sbom/tests.rs#L443) and [transitive_dependency_of](https://github.com/trustification/trustify/blob/9e274df6fe9e70eed01c05821dc03ada50d5ba5e/modules/ingestor/src/graph/sbom/tests.rs#L280).

Why?

**Comment by bobmcwhirter** [comment]
I suspect `$libdir` is being taken literally and not expanding.

**Comment by bobmcwhirter** [comment]
Dunno why though. Both are probably testing code that probably shouldn't even be in graph at this point.

**Comment by jcrossley3** [comment]
> I suspect `$libdir` is being taken literally and not expanding.

But why only with those tests? Are they doing anything particularly different than the other 40 tests?

**Comment by bobmcwhirter** [comment]
They, I suspect, are using the plpgsql stored function that we setup in the migration. But I dunno why pgsql would be "shelling out" for that. And they did work at some point, at least against a "real" Postgres install (via Docker).

**Comment by bobmcwhirter** [comment]
Which then leads me to believe it's probably a bug in the upstream embedded-postgres crate, mayhap.

**Comment by jcrossley3** [comment]
They also each worked prior to #174, when `Database::for_test` was used, but I can't figure out what the difference is in how the DB was created then and now.
