### ISSUE TITLE
PackageUrl versions are optional

### ISSUE THREAD

**Issue by ctron** [trustification/trustify#204]
We currently fail as we do require one

**Comment by bobmcwhirter** [comment]
Wait, do we? 

https://github.com/trustification/trustify/blob/main/common/src/purl.rs#L23

**Comment by ctron** [comment]
Yes, but we also have: https://github.com/trustification/trustify/blob/032d1d24d9990d3222b4860e9ca56b5314175d65/modules/ingestor/src/graph/package/mod.rs#L351-L353

**Comment by bobmcwhirter** [comment]
Ah, that's just possibly-wrong semantics on Graph stuff.

https://github.com/trustification/trustify/blob/032d1d24d9990d3222b4860e9ca56b5314175d65/modules/ingestor/src/graph/package/mod.rs#L331

"ingest_package_version" suggests that it's a versioned package being ingested as a child of the unversioned package.

**Comment by bobmcwhirter** [comment]
Which may or may no longer be an appropriate way to do it.

But PackageContext is pkg://maven/log4j/logj4, and PackageVersionContext then adds the version to pkg://maven/log4j/log4j@8675309.2
