### ISSUE TITLE
I found this while updating pg_embedded version to any 0.8.0+

### ISSUE THREAD

**Issue by helio-frota** [trustification/trustify#213]
![2024-04-29_09-58](https://github.com/trustification/trustify/assets/6443576/44bce89a-bca1-4d20-98e5-3826c61b4ecc)

Initially thinking that was related to 
`Breaking changes - define bootstrap superuser as postgres`
https://github.com/theseus-rs/postgresql-embedded/releases/tag/v0.9.0 

But it also happens with 0.8.0

**Comment by jcrossley3** [comment]
I've seen that occasionally, but I don't recall why. I don't see it now on my system. Does deleting your `.trustify/` help?

`$ rm -rf .trustify/`

**Comment by jcrossley3** [comment]
Is there something unusual about your OS or filesystem? Tough to debug without steps to reproduce.

**Comment by helio-frota** [comment]
No, fedora 39 basic xfce etc...
Thanks for jumping into this (also because we need that solved)
have you tried updating to `0.9.0` and see if works ?
thanks

**Comment by jcrossley3** [comment]
I do see the error with 0.9.0, yes.

**Comment by helio-frota** [comment]
searching o internet, the error points to rust std lib...

I found this diff on pg_emb:

![2024-04-29_11-51](https://github.com/trustification/trustify/assets/6443576/b07217e9-a55d-4f2f-8315-243c4aa05232)

updating to latest the error persists:

```console
➜  trustify git:(update-pg) ✗ cargo run --bin trustd
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
     Running `target/debug/trustd`
2024-04-29T15:06:57.529926Z  WARN trustd::db: Setting up managed DB; not suitable for production use!
Error: Invalid cross-device link (os error 18)
➜  trustify git:(update-pg) ✗ rustc --version
rustc 1.77.2 (25ef9e3d8 2024-04-09)
```

**Comment by helio-frota** [comment]
it will be solved with :+1: 
https://github.com/rust-lang/rustup/issues/3737#issuecomment-2081264673

**Comment by jcrossley3** [comment]
This fixes it for me: https://github.com/theseus-rs/postgresql-embedded/pull/58

**Comment by helio-frota** [comment]
great work the error gone !

```
➜  trustify git:(update-pg) ✗ cargo run --bin trustd
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
     Running `target/debug/trustd`
2024-04-29T18:53:34.497093Z  WARN trustd::db: Setting up managed DB; not suitable for production use!
2024-04-29T18:53:34.604099Z  INFO trustd::db: PostgreSQL installed in "/home/heliofrota/Desktop/tc/trustify/.trustify/postgres"
2024-04-29T18:53:34.604200Z  INFO trustd::db: Running on port 39423
2024-04-29T18:53:34.623816Z  INFO trustify_common::db: connect to postgres://trustify:trustify@localhost:39423/trustify
Error: Connection Error: error returned from database: password authentication failed for user "trustify"
Caused by:
	error returned from database: password authentication failed for user "trustify"
	error returned from database: password authentication failed for user "trustify"
	password authentication failed for user "trustify"
➜  trustify git:(update-pg) ✗ cat Cargo.toml | rg postgre
postgresql_embedded = { path = "/home/heliofrota/Desktop/postgresql-embedded/postgresql_embedded/"
```

**Comment by brianheineman** [comment]
This should be addressed in https://github.com/theseus-rs/postgresql-embedded/releases/tag/v0.9.1; thanks for the PR!
