### ISSUE TITLE
Implement other digests

### ISSUE THREAD

**Issue by ctron** [trustification/trustify#217]
See: https://github.com/trustification/trustify/pull/211/files … 

https://github.com/trustification/trustify/pull/211/files#diff-8addaea782a44f6263eb04d441519568c31098315e7269b71f5d4c125616e69aR97-R102

**Comment by bobmcwhirter** [comment]
I think we had an external contribution where the HashingRead now does 256/384/512, but we've not yet begun stuffing them into the db.
