### ISSUE TITLE
PM mode local time logs

### ISSUE THREAD

**Issue by helio-frota** [trustification/trustify#239]
As PM-mode is a thing to run locally, probably it makes more sense to print the local time
https://github.com/trustification/trustify/issues/225#issuecomment-2093686896

**Note:** After some attempts to get this by adding [this](https://rust-lang-nursery.github.io/rust-cookbook/development_tools/debugging/config_log.html#include-timestamp-in-log-messages) to the [main](https://github.com/trustification/trustify/blob/main/trustd/src/main.rs#L64)  (probably not the best location to add this, btw)

I noticed:

We need to enable `features = ["clock"]` 
`chrono = { version = "0.4.35", default-features = false, features = ["clock"] }`

We can print the local time without issues **(1)**

`println!("{}", Local::now());`

And we get this error `Error initializing logging: SetLoggerError(())` from `tracing.rs` **(2)**

![2024-05-06_10-29](https://github.com/trustification/trustify/assets/6443576/a63a0e43-faef-4259-968b-21ad66bc0577)

**Comment by jcrossley3** [comment]
Please don't add anything logger specific to `main`, which delegates all logger config to the `infrastructure` module. See the `init_tracing` calls in `db.rs`.

I suspect it's fine to configure local time there, but I defer to @ctron

**Comment by helio-frota** [comment]
ok thanks for the extra information @jcrossley3 :+1:

**Comment by ctron** [comment]
As @jcrossley3 said, the initialization of the logger/tracing happens in the infrastructure module. There are two variants, one when "tracing" is enabled, and all information is sent to an opentelemetry endpoint (in which case there's no logging on the console).

Or when "tracing" it not enabled, then everything goes to the console using this setup:

https://github.com/trustification/trustify/blob/b04474e306597e85df5bca9b8c964b75b037e285/common/infrastructure/src/tracing.rs#L147-L165

"Tracing" might not be the right term anymore, was "tracing" was "Tracing via Jaeger", which now actually is "Tracing via OpenTelemetry". "Tracing" itself is always present, it just might get routed to the console instead.

The output to the console happens via `tracing_subscriber::fmt::layer()`, which has some options. But I am not sure it has a timestamp format option. One thing to find out.

**Comment by helio-frota** [comment]
@ctron thank you for detailed information :+1:
