### ISSUE TITLE
OSV ingestor

### ISSUE THREAD

**Issue by bobmcwhirter** [trustification/trustify#247]
Whomever wants to wire up the OSV importers...

I don't think we should point it at osv.dev, as that's another layer of indirection.

Rather, we should point an importer-per-source, which just happen to be OSV-flavored.

https://google.github.io/osv.dev/data/

For instance, 

The RustSec advisory-db:

https://github.com/RustSec/advisory-db

**Comment by bobmcwhirter** [comment]
Bonus points...

For each useful importer, add a migration that inserts the relevant configuration into the DB, with disabled=false (perhaps?) so that when we get a handy-dandy Admin Console, someone can just tick the box to enable Rust/Python/etc OSV importers, instead of us having to tell them what URLs and configuration to put in each box.

**Comment by ctron** [comment]
I'll take a look.

**Comment by bobmcwhirter** [comment]
We have the loader for OSV variants, so that's good.

I'd prefer to ingest from each issuer's OSV-formatted repo, instead of pulling crap from osv.dev's APIs.

**Comment by ctron** [comment]
> We have the loader for OSV variants, so that's good.
> 
> I'd prefer to ingest from each issuer's OSV-formatted repo, instead of pulling crap from osv.dev's APIs.

Yup, I am close to that.

Point it to a git repo, it will clone that repo (or update it). Then take the diff from the last (commit) or start from the beginning. Ingesting all files (json or yaml) under a repo-local base path (or the root of the repo). Passing that on the OSV loader (ingestor).

I am just not sure about Rust's markdown frontmatter approach. I'll need to investigate that.

**Comment by bobmcwhirter** [comment]
Diff between `last_update` and `now` or sequentially walking each commit between?

Sequentially walking each commit could be cool, if we sort out versioning and temporal stuff.

**Comment by bobmcwhirter** [comment]
Rust has a "pure" OSV variant published also https://github.com/rustsec/advisory-db/tree/osv

**Comment by ctron** [comment]
> Diff between `last_update` and `now` or sequentially walking each commit between?
> 
> Sequentially walking each commit could be cool, if we sort out versioning and temporal stuff.

Taking the starting commit and FETCH_HEAD. Then creating a diff between those, recording all files. Iterating over the while list of files, but only processing the ones found in the diff.

**Comment by ctron** [comment]
I guess that what merged with #341. If not, we can re-open.
