### ISSUE TITLE
"filtering" requires an 'id' field

### ISSUE THREAD

**Issue by ctron** [trustification/trustify#267]
I ran into the issue of:

```
Error: query syntax error: Entity missing Id field
```

* It would be helpful if there would be the name of the entity that's missing that field.
* Why is that required?

**Comment by jcrossley3** [comment]
The only reason we currently require it is to ensure the order of the pagination results. So we can definitely relax that constraint and just omit the `ORDER BY Id` clause, trusting the caller to get the ordering correct.
