### ISSUE TITLE
Can we get rid of the "location" parameter?

### ISSUE THREAD

**Issue by jcrossley3** [trustification/trustify#273]
"remove location" I think should be a separate PR. Here, the issuer is *optional* and only used for OSV where that information is not necessarily derivable from the contents.

_Originally posted by @bobmcwhirter in https://github.com/trustification/trustify/pull/264#discussion_r1598774977_

**Comment by ctron** [comment]
The idea of the "location" was to be able to trace where this document came from. With the idea of being able to delete all related documents when the source gets deleted.

I think this relates to the question: how do we handle the case when two different users upload the same SBOM/advisory, and those users should be isolated?

**Comment by bobmcwhirter** [comment]
We did, yeah?

**Comment by jcrossley3** [comment]
> We did, yeah?

No. It's still hard-coded for advisories and required for SBOM's. We should agree on its value. Are the use cases @ctron cites above real?

**Comment by ctron** [comment]
I would say https://github.com/trustification/trustify/pull/442 closes this one.
