### ISSUE TITLE
Advisory Severity

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#277]
- Currently the only ones who have `severity` are Vulnerabilities. Technically, an Advisory can contain multiple Vulnerabilities.
- The Trustification (v1) UI has `aggregated severity` to define the severity of the advisory itself
![Screenshot from 2024-05-14 09-44-54](https://github.com/trustification/trustify/assets/2582866/2686fa34-fe19-4b7f-b8cc-977b1cc13d25)

- The question is: are we going to also have `aggregated severity`? If so, let's use this issue to track the work done in that regard.  If we won't have `aggregated severity` then let's document it here so the UI can also remove that column from the table (image below)

![Screenshot from 2024-05-14 09-43-08](https://github.com/trustification/trustify/assets/2582866/58b08339-379b-41d6-a706-1e1ddcc80171)

**Comment by ctron** [comment]
CSAF Spec: https://docs.oasis-open.org/csaf/csaf/v2.0/cs01/csaf-v2.0-cs01.html#3212-document-property---aggregate-severity

> Aggregate severity (aggregate_severity) of value type object with the mandatory property text and the optional property namespace is a vehicle that is provided by the document producer to convey the urgency and criticality with which the one or more vulnerabilities reported should be addressed. It is a document-level metric and applied to the document as a whole — not any specific vulnerability. The range of values in this field is defined according to the document producer's policies and procedures.

So I think there's value in this when viewing advisories. It's an indication, expressed by the advisory author, on how important the document is.

**Comment by carlosthe19916** [comment]
- On a more philosophical side. I always thought "Advisories" are a source of data/information but not worth showing it in the UI. An Advisory's data should serve to enrich metadata of other entities/models like "products", "sboms", "vulnerabilities" but no more.
- We do have a compromise in terms of "compatibility" between v1 and Trustify. So I support keeping Advisories as a main model/entity exposed through the APIs (and also in the UI). So if possible, we should be as close as we can to the v1 of Trustification (there might be deviations as we all know tought)

Just general thoughts :)

**Comment by ctron** [comment]
> * On a more philosophical side. I always thought "Advisories" are a source of data/information but not worth showing it in the UI. An Advisory's data should serve to enrich metadata of other entities/models like "products", "sboms", "vulnerabilities" but no more.

That's true to some degree. Ideally, you don't interact it with it.

Unless you reach a point where you want to understand "why" things are as they are. At this point it might make sense to direct the user to source of the information. And that's the ingested advisory, which contains the information as authored by the supplier.

**Comment by carlosthe19916** [comment]
The PR https://github.com/trustification/trustify/pull/300 has added "aggregated_severity" to advisories. That is a good first step. However, the `aggregated_severity` of each advisory obtained through `/api/v1/advisory` is `null`. So there is still work to do

**Comment by carlosthe19916** [comment]
Not sure in which PR it was been implemented by I can see a field `average_severity` in the Advisory entity
