### ISSUE TITLE
Should/can generate Vulnerability's CWE as metadata?

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#281]
Trustification exposes CWE in a column that exposes the list of vulnerabilities within a CSAF file. See image below:

![Screenshot from 2024-05-14 10-36-57](https://github.com/trustification/trustify/assets/2582866/78dddf04-a8b9-43f3-8e87-dfcce798e46e)

- Let's define if we should also include CWE on Trustify
- CWE is also a column defined in the original mockups designed by UX

**Comment by ctron** [comment]
The CWE indicates what the cause of the vulnerability is (<https://cwe.mitre.org/>). As it doesn't take up much space, I think there's value in showing this.
