### ISSUE TITLE
SBOM: get application "version" and spec "spdx|cyclonedx"

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#284]
- Trustification has a way of identifying the version of the application from which the SBOM was taken. See image below (the image belongs to Trustification):

![Screenshot from 2024-05-14 12-47-19](https://github.com/trustification/trustify/assets/2582866/76a5332b-2020-4a98-9bd2-ef294f0a715c)

- On the other hand, it would be beneficial to also have on a field the spec format to which the SBOM belongs to. e.g. spdx|cyclonedx

**Comment by ctron** [comment]
I think what would also make sense is to somehow have the "namespace" (unique ID). As an SBOM may have the same name/version, it might be hard to distinguish those. However, we might decide to not show it as prominent as the other fields.

On the other side, it might be an alternative to group "by name", show only the most recent, and provide the user with a sub-query to see older versions too.

**Comment by ctron** [comment]
Closed by https://github.com/trustification/trustify/issues/414

**Comment by carlosthe19916** [comment]
@ctron this issue was closed as "done". which are the fields that are supposed to be used in for rendering the "version" of an SBOM? I can only see a field `described_by.version` and `described_by` is an array; Are you saying a single SBOM can have multiple versions? 

![image](https://github.com/trustification/trustify/assets/2582866/0801c153-c02c-4215-94a6-31667e43f60d)

**Comment by ctron** [comment]
An SBOM doesn't always have a version. Not to be confused with the "version of the SBOM" or the "spec version of the SBOM".

CycloneDX can have a single defining component, which may have a version. SPDX has zero or more "describing" packages, which don't have a version, but which can have an external reference (like PURLs) which may have a version. That's also why some of our SBOMs have a version as part of the SBOM name.

Fun :)

I don't think the backend should make any modifications to the data when returning it. Just return what is known.

The UI can make this more user friendly on some overview screens (like tables). But should provide unaltered detail in more detailed screens.

So what could be done is to extract a single version from that response. If there's none, then there's none. If there's one, the situation is simple. If there are more than one, then the UI needs to get a little bit creating. I could imagine to show multiple, and then stop at some point with "and 5 more". Which will rarely be the case I guess.
