### ISSUE TITLE
Adding sort option for column that is sorted adds it twice

### ISSUE THREAD

**Issue by ctron** [trustification/trustify#298]
Example:

```rust
    #[test(tokio::test)]
    async fn custom_select() -> Result<(), anyhow::Error> {
        let query = advisory::Entity::find()
            .select_only()
            .column(advisory::Column::Id)
            .order_by_desc(advisory::Column::Id)
            .filtering(SearchOptions {
                q: "".to_string(),
                sort: "id".to_string(),
            })?
            .build(sea_orm::DatabaseBackend::Postgres)
            .to_string();

        assert_eq!(
            r#"SELECT "advisory"."id" FROM "advisory" ORDER BY "advisory"."id" DESC"#,
            query
        );

        Ok(())
    }
```

The result however is:

```
SELECT "advisory"."id" FROM "advisory" ORDER BY "advisory"."id" DESC, "advisory"."id" ASC
```

**Comment by jcrossley3** [comment]
My first thought about this is, "you're doing it wrong". If it's possible that a user would want to filter by `id:asc`, then why are we invoking `.order_by_desc(advisory::Column::Id)` at all?

Assuming it's just to ensure a stable ordering when the user doesn't pass a `sort` param, what should the correct behavior here be: asc or desc?

**Comment by jcrossley3** [comment]
Also, is the resulting SELECT wrong? Will it error? If it's harmless, do we care all that much?

**Comment by ctron** [comment]
Is it "wrong"? I think so. Does it execute: yes.

I think it is wrong in the sense that the filter won't apply. Assuming the query sets a default sort order (as discussed here: https://github.com/trustification/trustify/pull/295#issuecomment-2113081522), then that sort order would not get overridden by the user:

```sql
create table advisory (id int,location text );
insert into advisory (id, location) values (1, '1'), (2,'2');

SELECT "advisory"."location" FROM "advisory" ORDER BY "advisory"."id" DESC, "advisory"."id" ASC;
```

The result would be:

```
2
1
```

So the user would not have the ability to apply an alternate sort order.

**Comment by jcrossley3** [comment]
Then can we adopt the convention of invoking the default sort order *after* the `.filtering()` call? That way, the user has a chance to override it?

```rust
        let query = advisory::Entity::find()
            .select_only()
            .column(advisory::Column::Id)
            .filtering(q("").sort("id:asc"))?
            .order_by_desc(advisory::Column::Id)
            .build(sea_orm::DatabaseBackend::Postgres)
            .to_string();
        assert_eq!(
            r#"SELECT "advisory"."id" FROM "advisory" ORDER BY "advisory"."id" ASC, "advisory"."id" DESC"#,
            query
        );
```
As I understand how ORDER BY works, the 2nd clause will only have any effect if the 1st clause results in a tie.

**Comment by ctron** [comment]
Maybe it makes sense to pass some columns into the `filtering` method which define the default?

**Comment by jcrossley3** [comment]
> Maybe it makes sense to pass some columns into the `filtering` method which define the default?

Maybe. But I'm inclined to use the existing API unless there's a compelling reason not to. Which of these do you like better?

Currently, we have:
```rust
        let query = join_purls_and_cpes(query)
            .filtering(search)?
            .order_by_asc(sbom_package::Column::NodeId);
```
Is something like this better?
```rust
        let query = join_purls_and_cpes(query)
            .filtering(search.default_sort(sbom_package::Column::NodeId))?
```

**Comment by ctron** [comment]
I would prefer the latter one, as it ensure that it's correct.

I would prefer a different syntax though:

```rust
let query = join_purls_and_cpes(query)
  .filtering(search, &[sbom_package::Column::NodeId])?;
```

Because:

1. Default columns are a concept of the filtering, not the SearchOptions DTO.
2. It might be necessary to have more then one column.
