### ISSUE TITLE
It would be good to suppress this warning: `WARN actix_web_prom: Cannot build mixed cardinality pattern "/swagger-ui/{_:.*}"`

### ISSUE THREAD

**Issue by helio-frota** [trustification/trustify#302]
[Excluding](https://github.com/trustification/trustify/pull/274) `/swagger-ui/{_:.*}` from metrics [doesn't mean to suppress the log warning](https://github.com/trustification/trustify/issues/261#issuecomment-2108509183)

**Comment by helio-frota** [comment]
this fixes: https://github.com/nlopes/actix-web-prom/pull/83

**Comment by jcrossley3** [comment]
> this fixes: [nlopes/actix-web-prom#83](https://github.com/nlopes/actix-web-prom/pull/83) /cc @jcrossley3

I would say that's fixing the symptom, not the cause.

**Comment by helio-frota** [comment]
> I would say that's fixing the symptom, not the cause.

> Nice phrase, thanks

:heavy_plus_sign: 

https://github.com/trustification/trustify/pull/331

https://github.com/nlopes/actix-web-prom/pull/83#issuecomment-2126754117
