### ISSUE TITLE
Add aggregate_severity to advisory

### ISSUE THREAD

**Issue by bobmcwhirter** [trustification/trustify#306]
Judging from the CSAF spec 2.0: https://docs.oasis-open.org/csaf/csaf/v2.0/cs01/csaf-v2.0-cs01.html#3212-document-property---aggregate-severity

> Aggregate severity (aggregate_severity) of value type object with the mandatory property text and the optional property namespace is a vehicle that is provided by the document producer to convey the urgency and criticality with which the one or more vulnerabilities reported should be addressed. It is a document-level metric and applied to the document as a whole — not any specific vulnerability.

I would interpret this is an information covering the document itself, not it's vulnerabilities, nor their average.

_Originally posted by @ctron in https://github.com/trustification/trustify/issues/300#issuecomment-2115550064_

**Comment by carlosthe19916** [comment]
This Issue looks like a duplicate of https://github.com/trustification/trustify/issues/277 . Unless it is not a duplicate, let's close one of them to keep a good track of issues
