### ISSUE TITLE
Advisory[average_severity] should never be null

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#372]
After hitting `GET /api/v1/advisory` I got the following result (see image below):

![Screenshot from 2024-06-05 14-07-45](https://github.com/trustification/trustify/assets/2582866/e6f60cfe-9f14-4cf5-8e56-3d0e9a274b4b)

- If the vulnerability within the advisory has "severity=none" then the `average_severity` of the advisory itself should be `none` too. Why is it null? it does not look like an expected behaviour.

**Comment by ctron** [comment]
Taking a look at the CSAF spec, this field looks optional: https://docs.oasis-open.org/csaf/csaf/v2.0/csaf_json_schema.json

![image](https://github.com/trustification/trustify/assets/202474/1a8e6fbf-3909-469c-ac10-e2e218eaba3b)

**Comment by carlosthe19916** [comment]
@ctron Thanks for sharing it.
I ignore if all the other specs (osv, cve) also have the `aggregated_severity` as optional but although I understand that the CSAF spec has that field as optional, it looks bad when that kind of information is presented to the user:

- In the image below the vulnerabilities with `none` as severity have the gray color.
- Basically, from the UI, a human will read: "There is an advisory with vulnerabilities and although they are none, I would expect the `aggregated_severity` to be none".

I guess, technically, we could calculate the `aggregated_severity` if it is not set in the csaf file itself.
Again, I fully understand that we are following the spec, but this is the kind of things we need to evaluate and decide on how we will present data to the user and how our decision will impact the perception of the user. 

![Screenshot from 2024-06-05 15-17-02](https://github.com/trustification/trustify/assets/2582866/9e417625-37ef-465a-b20f-359033dd7737)

**Comment by ctron** [comment]
> I guess, technically, we could calculate the `aggregated_severity` if it is not set in the csaf file itself.

That would mean you have a vendor, making a statement. Signing that with their cryptographic key, so that you just override their statement?

Does that maybe have legal implications?

I really believe that's a bad approach.

**Comment by carlosthe19916** [comment]
- A crazy idea: If aggregated_severity=null then aggregated_severity="none"?
- I noticed that the only RH CSAF files that do not have aggregated severity are the ones with vulnerabilities classified as "none"

I think you are right in your points. But it does not make the UI (user perception) better. We, humans, see with our eyes and won't necessarily review the spec.

Now I am not sure If I should insist on this issue :) . On one hand you are right; on the other hand I still don't see the current UI friendly enough with missing aggregated_severity. I will need to give this a second though. Meanwhile, it would be nice to know what the others' opinions are, too.

**Comment by bobmcwhirter** [comment]
A `none` severity indicates a score of `0.0`. CVSS claims we shouldn't be seeing anything with a score of 0.0 (because is it actually a vulnerability if it has no impact?) but... it can (and does) happen.

On the other hand, not having an `aggregate_severity` is a choice by the CSAF authors, but does *not* indicate a zero-impact 0.0 score of `none`.

**Comment by carlosthe19916** [comment]
Closing this issue as it seems we will need to accept that a severity can be ZERO and also NULL
