### ISSUE TITLE
GET /api/v1/advisory/{key} requires a non deterministic {key}

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#377]
- If I hit `GET /api/v1/advisory` I get the JSON below as a response.
- The JSON has a field `hashes` which is an array of strings. My understanding is that we can use any of the values of the array as a `{key}` when we need to hit `GET /api/v1/advisory/{key}`

```json
{
  "items": [
    {
      "identifier": "RHBA-2024:1440",
      "hashes": [
        "sha256:2b56db5c3fa6365c20b56b9406c22eed0f3fca1b76e69112b300851fc5ed2474"
      ],
      "issuer": {
        "id": 1,
        "name": "Red Hat Product Security",
        "cpe_key": null,
        "website": null
      },
      "published": "2024-03-20T11:13:11Z",
      "modified": "2024-06-04T07:30:07Z",
      "title": "Red Hat Bug Fix Advisory: MTV 2.5.6 Images",
      "average_severity": "high",
      "average_score": 8.55,
      "vulnerabilities": []
    }
  ],
  "total": 754
}
```

- I don't think it is a good idea to expose an array of `hashes` for the client to decide which one to use, which value for the client we are adding exposing multiple `{key}`?
- The `hashes` array field can technically have ZERO elements, as it is an array, this just increases the complexity of any client to understand what is going on.
- What problem are we solving exposing multiple `hashes` through the REST API vs a single hash? I understand that multiple hashes can live in the backend, but the REST API must have only one `{key}`/`hash`

**Comment by bobmcwhirter** [comment]
In this case, I heartily disagree.

We keep an internal-only primary key for relations, but we don't want it to escape.

In this problem space, people use hashes/digests to unambiguously define content-addressable things.

Hashes, historically, have a finite lifespan before collisions, weaknesses or other degradations are discovered. 

So a single hash could be a *very bad thing*.

I think we can assure that `hashes` will contain always at least one entry, and the goal is to have at least 3 (sha256, 384 and 512) but quite possibly more.

The reason for supporting as many natural keys (all available hashes we can hash) is that at the other end of the stick, not from the UI, someone may be holding exactly a hash of exactly some specific algorithm, and are trying to discover exactly which advisory/sbom it applies to.

If SHA256 breaks next year, we can exclude it from the hashes, and continue to ship SHA384 and SHA512 are still valid hashes.

If we pick exactly one hash, we will be limiting our own future utility and options.

**Comment by carlosthe19916** [comment]
@bobmcwhirter I must disagree your disagreement :)

I will start highlighting that I am only looking at this from the client side; an application that uses the REST API. The UI is a client, there can be other application clients.

> Hashes, historically, have a finite lifespan before collisions, weaknesses or other degradations are discovered.
> So a single hash could be a very bad thing.

This is exactly why think this is a bad thing for clients that use the REST endpoints. Let me explain:
- The client is an application and not a human so the app will need to choose which `hash` to use to fetch a single advisory
  - So lets assume we arrive to a point where we have collisions on hashes
  - First step: I fetch the list of advisories by `GET /api/v1/advisory` and it gives a list of advisories. I choose one advisory and the hashes of that advisory are: [hash1, hash2, has3]
  - Second step: The client needs to fetch a single advisory fetching `/api/v1/advisory/{key}`. So the question is how the client (an application) will decide which one of the 3 hashes available to use? what is the algorithm to choose which one to use? This is the key question.

**Comment by jcrossley3** [comment]
> If SHA256 breaks next year, we can exclude it from the hashes, and continue to ship SHA384 and SHA512 are still valid hashes.
> 
> If we pick exactly one hash, we will be limiting our own future utility and options.

In the interest of "don't make me think", why force the user to choose the algorithm? Isn't excluding the SHA256 hash next year effectively the same as replacing all the SHA256 id's with SHA384 id's?

**Comment by bobmcwhirter** [comment]
`hashes[0]` I think can be guaranteed

**Comment by carlosthe19916** [comment]
> `hashes[0]` I think can be guaranteed

If that is the case why don't we set hashes[0] into its own field E.g.
```json
{
"default_hash": "hash[0]",
"hashes": [has1, hash2, hash3]
}

**Comment by bobmcwhirter** [comment]
> > If SHA256 breaks next year, we can exclude it from the hashes, and continue to ship SHA384 and SHA512 are still valid hashes.
> > If we pick exactly one hash, we will be limiting our own future utility and options.
> 
> In the interest of "don't make me think", why force the user to choose the algorithm? Isn't excluding the SHA256 hash next year effectively the same as replacing all the SHA256 id's with SHA384 id's?

Yes? Kinda? But `hashes[0]` should always be viable if not preferred.

The use-case I'm coming from is influenced by "integration with SigStore".

SigStore lets you sign hashes. It makes no assertion as to *which* hash algorithm you're using. And in fact you can use multiple.

So if I find something in SigStore, it'll tell me the hashes are `md5` and `sha512`.

Can we now find the related advisory if we only support `sha256` in the API?

**Comment by bobmcwhirter** [comment]
> > `hashes[0]` I think can be guaranteed
> 
> If that is the case why don't we set hashes[0] into its own field E.g.
> 
> ```json
> {
> "default_hash": "hash[0]",
> "hashes": [has1, hash2, hash3]
> } 
> ```

We could, but I fear that also implies that we think hash[0] is the "best" or "preferred". Instead, it's ... just an option.

**Comment by bobmcwhirter** [comment]
Also, some organizations may involve policies of "we only use sha512 for $reasons".

**Comment by carlosthe19916** [comment]
> > > `hashes[0]` I think can be guaranteed
> > 
> > 
> > If that is the case why don't we set hashes[0] into its own field E.g.
> > ```json
> > {
> > "default_hash": "hash[0]",
> > "hashes": [has1, hash2, hash3]
> > } 
> > ```
> 
> We could, but I fear that also implies that we think hash[0] is the "best" or "preferred". Instead, it's ... just an option.

Then we need to define which is the algorithm for choosing which one of the hashes any client will need to choose.
- Algorithm 1: always use hash[0] then it means we could apply what I suggested: having a field like `default_hash`
- Algorithm 2: I don't know...


I also need to ask, due to the collisions of hashes you mentioned. Does it mean that at some point `GET /api/v1/advisory/{hash[0]}` will return unexpected results? If so, how I client might know whether or not the hash he has been used has now collitions.

If there are multiple hashes, that is fine, but the client should not be forced to choose which one to choose. Also does not matter how big is the data, we should guarantee that ALL 100% of the hashes work FOREVER

**Comment by carlosthe19916** [comment]
> I would not be opposed to changing the internal PK to `uuid` (instead of auto-increment integer) and using that as the preferred key for the API, but continue to _also_ allow hash-based keys.

I think using UUID as the key is a better idea so if we want to fetch a single advisory we do:
`GET /api/v1/advisory/{uuid}`

On the other hand, if we want to fetch an advisory by hash we should do something like:
`GET /api/v1/advisory?q=hash=sha245:123456`

**Comment by ctron** [comment]
I don't want to over-complicate things, but I still struggle with the following:

```json
      "identifier": "RHBA-2024:1440",
      "hashes": [
        "sha256:2b56db5c3fa6365c20b56b9406c22eed0f3fca1b76e69112b300851fc5ed2474"
      ],
```

I would expect that "identifier" uniquely identified a resource/document.

However, that would not be the case here. As the advisory with that ID will change over time.

So when retrieving "by id", which ID do I use? The "identifier", which should give me the "most recent version of this document". Or "by hash", which would give me "that exact document".

I guess both use cases might be valid.

However, I would also prefer a single field (`id`, `uid`, …) which gives me access to that content. I think it's ok to offer additional "identifiers", or "references". But there should be a single one, making that decision for me.

**Comment by bobmcwhirter** [comment]
> > > > `hashes[0]` I think can be guaranteed
> > > 
> > > 
> > > If that is the case why don't we set hashes[0] into its own field E.g.
> > > ```json
> > > {
> > > "default_hash": "hash[0]",
> > > "hashes": [has1, hash2, hash3]
> > > } 
> > > ```
> > 
> > 
> > We could, but I fear that also implies that we think hash[0] is the "best" or "preferred". Instead, it's ... just an option.
> 
> Then we need to define which is the algorithm for choosing which one of the hashes any client will need to choose.
> 
> * Algorithm 1: always use hash[0] then it means we could apply what I suggested: having a field like `default_hash`
> * Algorithm 2: I don't know...
> 
> I also need to ask, due to the collisions of hashes you mentioned. Does it mean that at some point `GET /api/v1/advisory/{hash[0]}` will return unexpected results? If so, how I client might know whether or not the hash he has been used has now collitions.

If `sha256` breaks in the future, we then stop allowing `sha256:xxx` as a valid key. We still accept any non-broken hashes.

> 
> If there are multiple hashes, that is fine, but the client should not be forced to choose which one to choose. Also does not matter how big is the data, we should guarantee that ALL 100% of the hashes work FOREVER

Yeah, we simply cannot make that guarantee.  MD5 also used to be a perfectly usable hash. It still is in certain circumstances, but not for content-addressable security data.  Math and computer-science continue to progress, and sooner or later, all hashes may break.

Add in quantum computing, and the probability of future breakage only increases.

As a compromise, let's move to `uuid` for primary keys on advisories (and sboms, but I think @ctron already has done that), and allow `uuid:<uuid>` as a valid key.

But as an API consumer, if I can go straight from a `sha256:<sha256>` to the document I'm looking for, in a single call, that's entirely better than performing a search on a hash, to find the UUID, to finally do the lookup.

The `?q=hash=sha256:<sha256>` feels exceptionally dirty to me. First, `?q=` seems to me as an operation we do in order to retrieve zero-or-more results, and then I still have to sort through len=0, len=1, or len>1 cases for the results.

And if it's guaranteed to return exactly one item (or zero) then using the hash directly as a key seem sensible. I get the thing, or I get a 404. Pretty straight-forward.

**Comment by bobmcwhirter** [comment]
> I don't want to over-complicate things, but I still struggle with the following:
> 
> ```json
>       "identifier": "RHBA-2024:1440",
>       "hashes": [
>         "sha256:2b56db5c3fa6365c20b56b9406c22eed0f3fca1b76e69112b300851fc5ed2474"
>       ],
> ```
> 
> I would expect that "identifier" uniquely identified a resource/document.
> 
> However, that would not be the case here. As the advisory with that ID will change over time.
> 
> So when retrieving "by id", which ID do I use? The "identifier", which should give me the "most recent version of this document". Or "by hash", which would give me "that exact document".
> 
> I guess both use cases might be valid.
> 
> However, I would also prefer a single field (`id`, `uid`, …) which gives me access to that content. I think it's ok to offer additional "identifiers", or "references". But there should be a single one, making that decision for me.

Agreed. "Identifier" is the vuln or advisory identifier, without any guarantee of uniqueness.  CVEProject and RHT both issue advisories with identical identifiers these days.

And I also agree, a field named `uuid` would be more clear as "hey, here's a UUID you can use to uniquely and universally identify this document".

**Comment by jcrossley3** [comment]
I very much like the ability to easily fetch an advisory using a 3rd party's identifier, whether it looks like "RHBA-2024:1440" or any unique hash.

That our `/api/v1/advisory/{id}` returns _The Right Thing_ from the perspective of the user, whether that `id` is our `uuid` or someone else's `hash` will only garner trust from that user, I think.

**Comment by carlosthe19916** [comment]
This has been solved by https://github.com/trustification/trustify/pull/380
