### ISSUE TITLE
Keep one `.gitignore` ?

### ISSUE THREAD

**Issue by helio-frota** [trustification/trustify#39]
We have other `.gitignore` here: 
https://github.com/trustification/trustify/blob/main/frontend/.gitignore

Maybe just add the actual necessary changes to the root/.gitignore ?

**Comment by carlosthe19916** [comment]
I would like to avoid having "common files" between frontend and backend; frontend/backend share the same repository but no more. There is no reason to have files where one side can modify its content and affect the other side. Having multiple .gitignore files does not introduce bugs or drawback, on the contrary: brings independence on the folder where they are defined.

**Comment by helio-frota** [comment]
short: :+1: 
long: good description for me to stop thinking in another .gitignore file 

thanks!
