### ISSUE TITLE
Advisory search: Filter by average_severity does not work

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#401]
We need to be able to filter our advisories based on their severity: "none,medium, high, critical"

the query could be something like:
```
average_severity=medium|high
```

**Comment by bobmcwhirter** [comment]
@carlosthe19916 should be merged if you'd like to verify and close this issue.

**Comment by carlosthe19916** [comment]
Thanks @bobmcwhirter . I verified, this has been solved in the main branch and it is working as expected
