### ISSUE TITLE
What are the filters we support for Packages?

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#425]
If get hit `GET /api/v1/package?q=`

- Which are the current filters we support?
- The old trustification support the following filters (not saying we have to support the exact filters but we can use it as in inspiration)

![image](https://github.com/trustification/trustify/assets/2582866/2ccb6c1c-7311-4995-b58e-868b2b7215fd)

- Take into account that the current set of fields the api returs are mainly purls. e.g.

```json
{
  "items": [
      {
          "uuid": "f7d25fe0-2f5c-5feb-854f-762b7ecd6527",
          "purl": "pkg://npm/highlight-words-core@1.2.0",
          "base": {
              "uuid": "41de79a7-d36e-57e2-83ab-984875221b35",
              "purl": "pkg://npm/highlight-words-core"
          },
          "version": {
              "uuid": "f7d25fe0-2f5c-5feb-854f-762b7ecd6527",
              "purl": "pkg://npm/highlight-words-core@1.2.0",
              "version": "1.2.0"
          }
      }
  ],
  "total": 10263
}
```

**Comment by carlosthe19916** [comment]
I am asking how to construct the `q`.
- I want `rpm` packages. then `q=type=rpm` would work?
- I want `amd` architecture packages. Then `q=arch=amd` would work?
- etc.
That is not clear to me as so far we have been creating the `q` based on the fields of a model. But in this case the backend returns a PURL and not independent fields

**Comment by jcrossley3** [comment]
I think all the queries will use the LIKE operator, e.g. `q=purl~arch=amd`, `q=purl~pkg:rpm`. Some URL encoding will be required, I'm sure.

**Comment by jcrossley3** [comment]
Is this issue still relevant? If so, can you give me steps to reproduce? Thanks!

**Comment by carlosthe19916** [comment]
> Is this issue still relevant? If so, can you give me steps to reproduce? Thanks!

Let's close this issue. Yesterday it was agreeded that even the endpoint /api/v1/package will be gone.
If a more concrete issue appears I can create a new issue or reopen this one
