### ISSUE TITLE
/api/v1/vulnerabilities contains duplicate field names

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#543]
The `non_normative` fields are mentioned in the parent json field already. See image below.

![Screenshot from 2024-07-14 18-29-16](https://github.com/user-attachments/assets/c3537249-3a1b-4257-a51a-2683523ff5e1)

**Comment by jcrossley3** [comment]
I think this is working as designed. The values of the normative fields (from the Vulnerability) may differ from those of the non-normative fields (from the Advisory). Is that correct @bobmcwhirter?

**Comment by carlosthe19916** [comment]
I see... perhaps it deserves a deeper discussion then. Ideally the API should expose a reasonable abstraction of all the internal data. So what if `description` != `non_normative.description`? Shouldn't the REST endpoints abstract those cases and only expose a single `description` deciding internally which one has precedence e.g. `description` has higher priority in respect to `non_normative.description`?

**Comment by carlosthe19916** [comment]
Or I might've been not fully understanding the meaning of `non_normative`. Perhaps it might be matter of renaming fields to a more meaningful name? i might be wrong, as always :)

**Comment by jcrossley3** [comment]
We could collapse them into this, maybe:
```
      "vulnerabilities": [
        {
          "cwe": "string",
          "description": "string",
          "discovered": "2024-07-15T20:41:34.298Z",
          "identifier": "string",
          "modified": "2024-07-15T20:41:34.298Z",
          "normative": true,
          "published": "2024-07-15T20:41:34.298Z",
          "released": "2024-07-15T20:41:34.298Z",
          "title": "string",
          "withdrawn": "2024-07-15T20:41:34.298Z",
          "score": 0,
          "severity": "string"
        }
      ]
```
So the backend would populate those fields from the Vulnerability if it exists (normative=true) or if it doesn't, the Advisory (normative=false). We could do that easily enough, but I'd want to answer 2 questions beforehand:

1. Will the user ever care to see the non-normative fields if both entities exist?
2. Should we account for potentially multiple advisories, i.e. do we need an array of non-normative entities?

**Comment by carlosthe19916** [comment]
This is my personal opinion, not an official one, so I encourage all to disagree :)

> Will the user ever care to see the non-normative fields if both entities exist?

A user does not care whether or nor there are non-normative fields, he only cares to see a single description|title that describes the Vulnerability he is looking at. I doubt the user will be interested in looking at descriptions|titles twice (the non_normative one and the parent one). In case there are two different titles|descriptions (the default and non-normative) the user will be interested in read the most accurate one (the one the server thinks is more accurate) or a new title that summarizes the two titles|descriptions in a single one (like a human would do when it comes to merge 2 sentences)

> Should we account for potentially multiple advisories, i.e. do we need an array of non-normative entities?

Just like I mentioned in my reply above, I believe a user wants to see only one `discovered, modified, published, released, withdrawn, etc` fields regardless of the fact that there might be multiple Advisories having an opinion about the vulnerability

The only exception where it might be important to have an array of non-normative entities would be the case of `score & severity`. E.g. Advisory 1 says it has medium severity but Advisory 2 says it has High severity.

**Comment by bobmcwhirter** [comment]
I'd vote dropped non normative info and guide folks to ingesting CVEs.
