### ISSUE TITLE
Handling loops in relationships

### ISSUE THREAD

**Issue by ctron** [trustification/trustify#553]
While writing up some text about external references, I came across the problem that, with transitive fetches of packages, we might run into the problem of an infinite loop. However, that problem doesn't seem to be different with internal references.

I am not aware that we're handling this right now. When fetching a single level of relationships, that's not a problem. But for recursive operations, it assume it will be.

**Comment by bobmcwhirter** [comment]
fwiw, I've not yet had the need for transitive fetches. Weirdly haven't found a use for it yet.

**Comment by ctron** [comment]
I tried a few things, but everything was working fine. So maybe it's not a problem after all.
