### ISSUE TITLE
Implement REST Endpoints needed for the UI

### ISSUE THREAD

**Issue by gildub** [trustification/trustify#56]
Required REST endpoints for trustify-ui
- [ ] SBOMs
- [ ] CVEs
- [ ] Advisories
- [ ] Packages

**Comment by gildub** [comment]
We need to hold on the implementation until we have an answer about using GraphQL or REST API.

**Comment by carlosthe19916** [comment]
@gildub I hope you agree closing this ticket. There are/were other issues for specific REST endpoint definitions so they are better tracked in their or issues
