### ISSUE TITLE
Ensure correct error handling for str-purl conversions

### ISSUE THREAD

**Issue by jcrossley3** [trustification/trustify#6]
I think the answer is TryFrom instead since failure is an option.

_Originally posted by @bobmcwhirter in https://github.com/trustification/trustify/pull/3#discussion_r1513538151_

Converting to `TryFrom` has rippling effects that bring into question the existence of both `Purl` and `PackageUrl` types, as well as their corresponding `PurlErr` and `packageurl::Error` types, not to mention the `system::Error` type.

**Comment by jcrossley3** [comment]
@bobmcwhirter why both `Purl` and `PackageUrl`? Can we justify our NIH?

**Comment by bobmcwhirter** [comment]
I think originally I wanted an owned type without a lifetime.
