### ISSUE TITLE
When dump/restore of the database there are some viloate foreign key constraint errors

### ISSUE THREAD

**Issue by JimFuller-RedHat** [trustification/trustify#603]
Example errors when attempting to restore trustify data dump from embedded_pg.

'''
ERROR:  insert or update on table "advisory" violates foreign key constraint "advisory_issuer_id_fkey"
DETAIL:  Key (issuer_id)=(89322b41-321b-4b83-9ee1-9f86c1d7c343) is not present in table "organization".
'''

'''
ERROR:  insert or update on table "package_relates_to_package" violates foreign key constraint "package_relates_to_package_relationship_fkey"
DETAIL:  Key (relationship)=(0) is not present in table "relationship".
'''

'''
ERROR:  insert or update on table "product_version" violates foreign key constraint "product_version_sbom_id_fkey"
DETAIL:  Key (sbom_id)=(0190a643-75a5-7373-87fd-3a302dc1ca78) is not present in table "sbom".
'''

The sign of a healthy data layer is one that exports and imports with no errors.

**Comment by bobmcwhirter** [comment]
Does this indicate we're missing some FK constraints to tell pgsql which order to import tables?

`organization` should import before `advisory`.

**Comment by JimFuller-RedHat** [comment]
I have rarely seen pg_backup get it wrong so it is possible we are missing something.

I will try to rearrange dump to see if it works and confirm this is solely and ordering issue.

**Comment by chirino** [comment]
Any tips on how to recreate that DB to a state where we can reproduce? Are there certain docs we need to ingest?

**Comment by JimFuller-RedHat** [comment]
I have a sql dump from @ctron - get it from him or I can next week

**Comment by jcrossley3** [comment]
If still an issue, re-open with a repro test case, please
