### ISSUE TITLE
prefix trustify env vars to avoid collision

### ISSUE THREAD

**Issue by JimFuller-RedHat** [trustification/trustify#620]
either TRUSTIFY_ or TRUSTD_ works ?

**Comment by helio-frota** [comment]
for ref https://github.com/trustification/trustify/blob/main/docs/env-vars.md

**Comment by JimFuller-RedHat** [comment]
I think in the end TRUSTD prefix applies to prod operational or things we want to avoid collision (eg. with postgres for example) ...  no need to enforce consistently everywhere  ... closing this
