### ISSUE TITLE
`cargo xtask generate-dump -o dumppp.sql` -- I can't find the `dumppp.sql` file

### ISSUE THREAD

**Issue by helio-frota** [trustification/trustify#649]
Not sure if I'm using this command wrong or missing any previous step :+1: 

![2024-08-06_16-09](https://github.com/user-attachments/assets/8c6604cd-b38e-478b-b722-2788b80821d1)

`Error: No such file or directory (os error 2)` ^ don't know if it is related 

searching with `fzf`, nothing found

![2024-08-06_16-11](https://github.com/user-attachments/assets/dcb7bac0-f314-4fc2-a4be-1063ff7b35bf)

**Comment by ctron** [comment]
It looks like it failed to export. Not sure why though.

**Comment by helio-frota** [comment]
thanks I'll take a look again :+1:

**Comment by helio-frota** [comment]
the fix https://github.com/trustification/trustify/pull/908
