### ISSUE TITLE
Validate sboms during import

### ISSUE THREAD

**Issue by dejanb** [trustification/trustify#701]
We might consider validating sbom files during ingestion. We do that in trustification to be sure document id is present. I'm not sure yet how that is critical to trustify data model, but it would make sense to so that.
If we do it, we should be aware of https://github.com/CycloneDX/cyclonedx-rust-cargo/issues/737 which needs a workaround for now.

**Comment by ctron** [comment]
I think we already do that to some degree in trustify too. We also report back these findings via "error" or "warning" from the ingestion process.

When triggered by an importer, those results are present in the import report. When calling the REST API for ingesting a new document, those findings come back via the API call.

We can for sure add more validations, but there are some in place like: SPDX license expression, missing or duplicate package IDs.

**Comment by ctron** [comment]
e.g.:

* https://github.com/trustification/trustify/blob/2508c7cef313db5c9ef3cadbba5fd40ae45bcf9a/modules/ingestor/src/graph/sbom/spdx.rs#L217-L227
* https://github.com/trustification/trustify/blob/2508c7cef313db5c9ef3cadbba5fd40ae45bcf9a/modules/ingestor/src/graph/sbom/spdx.rs#L307

**Comment by JimFuller-RedHat** [comment]
agreed, closing this as I think both the spirit and letter of format level validation is being applied here.
