### ISSUE TITLE
heads-up: pg-emb `1.16x` breaks our build with `xz2` libzma

### ISSUE THREAD

**Issue by helio-frota** [trustification/trustify#704]
I'm not 100% sure but I think this commit is causing it

* clone pg-emb
* `git show 6d5ec7dc15bafacb32ac183a7c85ca25df72f588`

**Comment by helio-frota** [comment]
related things:

* https://github.com/trustification/trustify/pull/496
* https://github.com/trustification/trustify/pull/508
* https://github.com/trustification/trustify/pull/536

**Comment by helio-frota** [comment]
Depends on updating to rust 1.80.x https://github.com/trustification/trustify/issues/703

**Comment by ctron** [comment]
* https://github.com/theseus-rs/postgresql-embedded/issues/132
* https://github.com/theseus-rs/postgresql-embedded/pull/133

**Comment by helio-frota** [comment]
thanks @ctron https://github.com/theseus-rs/postgresql-embedded/releases/tag/v0.16.3
