### ISSUE TITLE
clearly defined data

### ISSUE THREAD

**Issue by ctron** [trustification/trustify#743]
While taking a look a data from clearly defined, I noticed that we are actually only processing the "curated" data, but not the "harvested" data.

**Comment by bobmcwhirter** [comment]
The only harvested data I could find was... very out of date?

https://github.com/clearlydefined/harvested-data

Last commit 6 years ago.

Maybe it's only available via an API call, instead of a git clone?

**Comment by ctron** [comment]
I assume that's the case. Maybe we should reach out and create a strategy.

**Comment by bobmcwhirter** [comment]
I'll try to join their dev mtg next Wednesday.

https://docs.clearlydefined.io/docs/community/meetings

I can't find a reasonable contact email.
