### ISSUE TITLE
Excessive memory use of graphql endpoint

### ISSUE THREAD

**Issue by ctron** [trustification/trustify#750]
While working on the loadtests, I noticed excessive memory usage of the `trustd` API process. I had to increase the memory for `trustd` from 2 GiB to 16 GiB to have it success at least once.

It turned out that the culprit was the grapgql endpoint. Disabling those tests made the loadtest success with 2 GiB.

While I do understand that just disabling the tests isn't the best idea, it's the only one that works for running those tests on the GitHub CI, as we only have 7 GiB total there.

On the other side, if a single graphql user can cause a memory consumption of more than 10 GiB, then I think we have a problem that needs to be addressed.

I would propose the following steps:

* https://github.com/trustification/trustify/pull/751
* Improve the memory consumption of the grapgql endpoint

**Comment by JimFuller-RedHat** [comment]
Alternately - in the future we might consider a (read only) graphql interface built on top of a graph representation- that will probably be more _contained_ in terms of memory usage. Otherwise maintaining a graphql on top of relational models may mean we have to constrain interface to avoid problematic usage areas.

**Comment by bobmcwhirter** [comment]
tagging @gildub to investigate

**Comment by helio-frota** [comment]
Things found during the tests
* https://gist.github.com/helio-frota/a17be4519732c4a674f08dbefd7dd9fc
* The default compose pg config failed with 256 goose users
* Feel free to do the same with this step by step https://github.com/trustification/scale-testing/pull/33

```
2024-10-17T19:12:56.507148Z  INFO ThreadId(01) run: trustify_module_importer::server: return=Err(
    Database(
        ConnectionAcquire(
            Timeout,
        ),
    ),
)
2024-10-17T19:12:56.508014Z  INFO ThreadId(01) trustify_server: one of the server tasks returned, exiting: Err(database error: Failed to acquire connection from pool: Connection pool timed out

Caused by:
    0: Failed to acquire connection from pool: Connection pool timed out
    1: Connection pool timed out)
Error: database error: Failed to acquire connection from pool: Connection pool timed out
Caused by:
	Failed to acquire connection from pool: Connection pool timed out
	Connection pool timed out
heaptrack stats:
	allocations:          	79697266
	leaked allocations:   	505701
	temporary allocations:	11053581
```

The results shows something with vulnerability feature

![2024-10-17_16-18](https://github.com/user-attachments/assets/9748f5c2-087b-4b50-8920-7905c1d72950)

**Comment by helio-frota** [comment]
We are doing a `select * from vulnerabilities` and this returns 23k+ rows, those rows are transformed/parsed/serialized/etc later via graphql -- the 'select' itself according to heaptrack is about ~45MiB and then... again according to heaptrack it gets transformed into ~215MiB when passing through grahpql bits 

>  I had to increase the memory for trustd from 2 GiB to 16 GiB to have it success at least once.

I couldn't simulate this behavior yet, maybe I need to run the tests with the same amount of time.

**Comment by helio-frota** [comment]
* `➜  trustify git:(the-dump)` this is a branch I'm using for the tests so we have more commits when comparing with `main`, but we can't discard a possibility of this problem has been solved over time.

```console
➜  trustify git:(the-dump) git log --since="2024-09-04" --until="today" -G "advisory" --oneline --pretty=format:"%ad | %h %s" --date=format:"%Y-%m-%d %H:%M:%S"
2024-10-18 10:54:52 | 03e2637 fix: performance issue in update_deprecated_advisory
2024-10-09 20:01:55 | 9481c8d refactor: Convert version scheme into an enum
2024-10-08 16:41:00 | 071d579 chore: implement other version schemes using an exact match
2024-10-14 11:28:58 | 109a45c fix typo
2024-10-07 12:09:52 | 5d02060 feat: create versioned purls from OSV
2024-10-04 10:36:27 | 9670a18 chore(ai): split out the tools into their own files
2024-10-01 13:26:45 | d5f3e2c test: add some basic update tests for OSV
2024-09-30 17:14:02 | de7b255 test: add some basic update tests for CVEs
2024-10-03 07:50:11 | b91f273 [ai]: use json to produce better structured output in the ai tools results.
2024-10-02 14:33:43 | d37335b chore: use function suggested by @JimFuller-RedHat
2024-10-02 11:17:36 | 3a2701d chore: changes according to feedback from the PR review
2024-09-30 15:58:32 | f542219 fix: use a combination of namespace and tracking id as document id
2024-09-25 14:26:21 | 3123d2b feat: deprecate advisories when receiving an upload or deleting one
2024-09-23 13:54:14 | 83e4999 test: add a test for ingesting an updated CSAF document
2024-08-14 12:41:02 | 2c55fde feat: ingest products from csaf documents
2024-09-27 11:37:59 | 483b7db Add an SbomInfo tool.
2024-09-27 08:26:11 | 53447f7 Fixing test failures, other small cleanups.
2024-09-26 20:28:24 | 3d3fba6 Improving prompts.
2024-09-26 16:03:17 | a239013 Improve the AI tools to provide more information
2024-09-17 14:49:44 | 9145a6e fix: prevent uploading compressed files which might exhaust the memory
2024-09-17 07:11:12 | eaf2703 chore: reusing sample_advosiry ingestion function
2024-09-12 13:43:10 | 64874d4 Break out SHAs from Advisory and SBOM and plonk them into a SourceDocument. Handle down migrations appropriately. Auto-gen the PK for `source_document` table. Adjust to better multi-model adjustments. LESS LOGGING PLEASE. Regen openapi.
2024-09-16 13:04:36 | 600dd36 fix: store documents when ingesting a dataset
2024-09-16 10:42:13 | 3cc7b55 chore: reduce the amount of data
2024-09-13 08:12:51 | 14c356c feat: support compressed upload
2024-09-11 11:21:53 | 9722fdc feat: allow importing complete datasets
2024-09-09 15:11:11 | 54da44c fix: allow ingesting YAML based OSV
2024-09-05 15:45:58 | ff0fdd0 Apply heuristics to divine pURLs from CVERecords iff possible.
2024-09-04 15:13:32 | 7fb1c67 Regen openapi.yml.
2024-09-04 14:58:15 | 5a3d71c Add some one-liner API documentation for the UI.
```

* At the time this issue was created, there was only one *advisory* test in the loadtests repo. I added the other [tests](https://github.com/trustification/scale-testing/commit/181779c4bb5b445be5f5f67ee004622552407a78) later.
* The max mem usage according with the heaptrack was related with *vulnerability*
* The max time I ran the tests was 20 minutes and the memory continued the same without increase over time

@ctron makes sense to close this issue and re-open in case happen again in future ?

**Comment by ctron** [comment]
Good question. I don't think we did much on the graphql area lately. So I'd wonder if this really is fixed, or if we just test it the wrong way.

If we are indeed selecting all vulnerabilities, then the tests we have might no actually capture this, as most tests will have less than 5 I guess.

> * The max time I ran the tests was 20 minutes and the memory continued the same without increase over time

I'd actually expect it to stay the same, the question is just, on what level/amount is it? If that's ~1 GiB, ok (maybe not). But if it's 10GiB, we definitely have an issue.

I think it would be good to have an understanding of how much memory our operations consume, with a populated datastore. I think we can leverage the scale-tests for that, as there's a workflow which tests with an fully populated database.

So maybe run those tests locally, enabling graphql again, and limiting the container resources to see what is required to have them pass: https://github.com/trustification/trustify-load-test-runs/blob/e7eaa5879356993339b944ccfd03173d9e592bb1/compose.yaml#L160-L166

If the tests pass with 2 GiB, let's close the issue. If they don't, we should investigate.

**Comment by helio-frota** [comment]
> Good question. I don't think we did much on the graphql area lately.

Thanks for the feedback I don't feel comfortable in closing the issue without a clear solution so any extra feedback is good.

> So I'd wonder if this really is fixed, or if we just test it the wrong way.

+1 the test I did was using most code isolation as possible focusing on graphql functions targeting the `graphql/` endpoint only with a populated database.

> If we are indeed selecting all vulnerabilities, then the tests we have might no actually capture this, as most tests will have less than 5 I guess.

sorry I'm not 100% following this part, I generated a dump with `cargo xtask` , populated the database, and executed the https://github.com/trustification/scale-testing test

> I'd actually expect it to stay the same

Good we have this then.

> the question is just, on what level/amount is it? 

We have an answer for this

![2024-10-29_07-05](https://github.com/user-attachments/assets/28c1c082-ae3f-41d6-b166-3d44e7919914)

> If that's ~1 GiB, ok (maybe not). But if it's 10GiB, we definitely have an issue.

I agree

> So maybe run those tests locally, enabling graphql again, and limiting the container resources to see what is required to have them pass: https://github.com/trustification/trustify-load-test-runs/blob/e7eaa5879356993339b944ccfd03173d9e592bb1/compose.yaml#L160-L166

Here we have a conflict/disagreement point, which is good :+1: because we can find more things 

* I'm not using keycloack on the tests I shared
* I'm not running trustify same way you ran here https://github.com/trustification/trustify-load-test-runs/blob/e7eaa5879356993339b944ccfd03173d9e592bb1/Containerfile.trustify#L16
* The tests I ran with goose avoided hitting `logon` and https://github.com/trustification/scale-testing/pull/33/files#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcR106-R121
* Again isolated as possible focusing on graphql functions targeting the `graphql/` endpoint only

**Comment by ctron** [comment]
> > If we are indeed selecting all vulnerabilities, then the tests we have might no actually capture this, as most tests will have less than 5 I guess.
> 
> sorry I'm not 100% following this part, I generated a dump with `cargo xtask` , populated the database, and executed the https://github.com/trustification/scale-testing test

Sorry, what I was trying to say was: Today, we don't seem to have any unit/integration tests which have more than just a hand full of advisories. So we won't see this as part of running something like `cargo test`. Jim added some heap tracking IIRC for those tests. But they're not covering this.

Using the scale-test with a pre-populated database (as you did) seems sufficient for this investigation. But it's not covering the day-to-day CI tests. Which is ok, but room for improvement.

So, maybe run the tests with the docker resource limits (and graphql) and see if that fails (due to OOM) or succeeds. If it succeeds, let's re-enable this in the CI and see what happens.

**Comment by helio-frota** [comment]
Sounds good I'll use https://github.com/trustification/trustify-load-test-runs locally and if I find issues I'll create there

**Comment by helio-frota** [comment]
it worked https://github.com/trustification/trustify-load-test-runs/issues/2#issuecomment-2450763074

**Comment by helio-frota** [comment]
it worked with both `RestAPIUser,GraphQLUser`

```
- --scenarios
- RestAPIUser,GraphQLUser
```

```
 Name                     |                                        Status codes
 ------------------------------------------------------------------------------
 GET get_advisory_by_do.. |                                         6,845 [200]
 GET list_advisory        |                                         6,846 [200]
 GET list_advisory_pagi.. |                                         6,846 [200]
 GET list_importer        |                                         6,845 [200]
 GET list_organizations   |                                         6,846 [200]
 GET list_packages        |                                         6,845 [200]
 GET list_packages_pagi.. |                                         6,845 [200]
 GET list_products        |                                         6,845 [200]
 GET list_sboms           |                                         6,845 [200]
 GET list_sboms_paginated |                                         6,845 [200]
 GET list_vulnerabilities |                                         6,845 [200]
 GET list_vulnerabiliti.. |                                         6,845 [200]
 GET search_packages      |                                         6,845 [200]
 POST g_cves_by_sbom      |                                         5,240 [200]
 POST g_get_advisories    |                                         5,240 [200]
 POST g_get_advisory_by.. |                                         5,240 [200]
 POST g_get_organizatio.. |                                         5,240 [200]
 POST g_get_sbom_by_id    |                                         5,240 [200]
 POST g_get_sbom_by_lab.. |                                         5,240 [200]
 POST g_get_vulnerabili.. |                                         5,240 [200]
 POST g_get_vulnerabili.. |                                         5,240 [200]
 -------------------------+----------------------------------------------------
 Aggregated               |                                       130,908 [200]
 ```
 
 Then I reduced the resources to:
 
 ```diff
 --- a/compose.yaml
+++ b/compose.yaml
@@ -21,11 +21,11 @@ services:
     deploy:
       resources:
         reservations:
-          cpus: "2"
-          memory: 2G
+          cpus: "1"
+          memory: 1G
         limits:
-          cpus: "2"
-          memory: 2G
+          cpus: "1"
+          memory: 1G
     healthcheck:
       test: [ "CMD", "pg_isready", "-h", "localhost", "-U", "postgres", "-d", "trustify" ]
       interval: 2s
@@ -102,7 +102,7 @@ services:

         echo "Importing dump"

-        curl --retry 50 --retry-max-time 3600 -sSL https://trustify-dumps.dentrassi.de/dump.sql.gz -o dump.sql.gz
+        zcat /home/heliofrota/Desktop/tc/dump.sql.gz | psql
         zcat dump.sql.gz | psql
         echo "VACUUM ANALYZE; REINDEX database trustify;" | psql

@@ -135,6 +135,7 @@ services:
       dockerfile: ./Containerfile.trustify

     environment:
+      TRUSTD_WITH_GRAPHQL: "true"
       TRUSTD_DB_USER: postgres
       TRUSTD_DB_PASSWORD: eggs
       TRUSTD_DB_HOST: postgres
@@ -159,11 +160,11 @@ services:
     deploy:
       resources:
         reservations:
-          cpus: "3"
-          memory: "2G"
+          cpus: "2"
+          memory: "1G"
         limits:
-          cpus: "3"
-          memory: "2G"
+          cpus: "2"
+          memory: "1G"

   loadtests:
     depends_on:
@@ -194,4 +195,4 @@ services:
       - --baseline-file
       - /baseline/baseline.json
       - --scenarios
-      - RestAPIUser
+      - RestAPIUser,GraphQLUser
```

Continue working but got some errors not related to OOM

```
 === ERRORS ===
 ------------------------------------------------------------------------------
 Count       | Error
 ------------------------------------------------------------------------------
 7             GET search_packages: error sending request search_packages: client error (Connect)
 7             GET list_sboms: error sending request list_sboms: client error (Connect)
 7             GET list_products: error sending request list_products: client error (Connect)
 7             GET list_packages_paginated: error sending request list_packages_paginated: client error (Connect)
 6             GET list_sboms_paginated: error sending request list_sboms_paginated: client error (Connect)
 5             GET list_packages: error sending request list_packages: client error (Connect)
 4             POST g_get_vulnerability_by_id: error sending request g_get_vulnerability_by_id: client error (Connect)
 4             POST g_get_vulnerabilities: error sending request g_get_vulnerabilities: client error (Connect)
 4             POST g_get_sbom_by_labels: error sending request g_get_sbom_by_labels: client error (Connect)
 4             POST g_get_sbom_by_id: error sending request g_get_sbom_by_id: client error (Connect)
 4             POST g_cves_by_sbom: error sending request g_cves_by_sbom: client error (Connect)
 4             GET list_vulnerabilities_paginated: error sending request list_vulnerabilities_paginated: client error (Connect)
 4             GET list_vulnerabilities: error sending request list_vulnerabilities: client error (Connect)
 4             GET list_organizations: error sending request list_organizations: client error (Connect)
 4             GET list_importer: error sending request list_importer: client error (Connect)
 4             GET list_advisory_paginated: error sending request list_advisory_paginated: client error (Connect)
 4             GET list_advisory: error sending request list_advisory: client error (Connect)
 4             GET get_advisory_by_doc_id: error sending request get_advisory_by_doc_id: client error (Connect)
 3             POST g_get_organization_by_name: error sending request g_get_organization_by_name: client error (Connect)
 3             POST g_get_advisory_by_id: error sending request g_get_advisory_by_id: client error (Connect)
 3             POST g_get_advisories: error sending request g_get_advisories: client error (Connect)
 ------------------------------------------------------------------------------
 ```

**Comment by helio-frota** [comment]
> So, maybe run the tests with the docker resource limits (and graphql) and see if that fails (due to OOM) or succeeds. If it succeeds, let's re-enable this in the CI and see what happens.

@ctron I think we can close this :+1: I ran the tests with 1GB memory and both scenarios (previous comment^)
