### ISSUE TITLE
Finding an advisory by its document ID

### ISSUE THREAD

**Issue by ctron** [trustification/trustify#752]
Advisories have "unique" IDs in their documents. At least, they should be unique. For SBOMs, every newly generated SBOM must have a new ID. For CSAF, documents get updated, keeping their ID.

Taking a look at our API, I can "get all advisories". That will return me a list of advisories, providing me both "hashes", a "uuid", as well as an "identifier". The "identifier" being the "document ID". However, that is not necessarily unique in our system. Either due to "bad data" (SBOMs) or due to updates (CSAF).

However, when I want to "get" information about an advisory, I must provide either the UUID, or a digest of the original document.

Coming from a perspective where I do have the "document ID", there currently doesn't seem to a way to: "get all advisories with this document id". And I think we should have that.

**Comment by jcrossley3** [comment]
Doesn't `/api/v1/advisory?q=DOCUMENT_ID` return what you're describing?

**Comment by ctron** [comment]
> Doesn't `/api/v1/advisory?q=DOCUMENT_ID` return what you're describing?

No because that would search all fields for `DOCUMENT_ID`, which not the same as searching for `identifier = DOCUMENT_ID`.

**Comment by jcrossley3** [comment]
Probably amounts to the same results (and possibly more interesting to the user) but you could also call `/api/v1/advisory?q=identifier%3dDOCUMENT_ID`

**Comment by ctron** [comment]
I wasn't aware of this, good we already have it.
