### ISSUE TITLE
Unable to ingest valid spdx file

### ISSUE THREAD

**Issue by jcrossley3** [trustification/trustify#762]
[v22spdx.json](https://github.com/user-attachments/files/16897128/v22spdx.json)

**Comment by JimFuller-RedHat** [comment]
To confirm this spdx validates ... maybe it is the NOASSERTION for downloadlocation ... FWIW it might be useful to throw validation errors only on SPDX validation ... then we could consider raising a different error for any semantic rules/conventions we expect SBOM to conform to.

**Comment by ctron** [comment]
This results in:

```json
{"error":"Ingestor error","message":"Invalid SPDX reference: NOASSERTION"}
```

**Comment by ctron** [comment]
The file has a reference of:

```json
{
    "spdxElementId" : "SPDXRef-CommonsLangSrc",
    "relatedSpdxElement" : "NOASSERTION",
    "relationshipType" : "GENERATED_FROM"
  }
```

However, I can't seem to find any element with an ID of: `NOASSERTION`. Maybe it's something we're missing. I'll check the spec.

**Comment by JimFuller-RedHat** [comment]
maybe related to https://github.com/trustification/trustify/issues/552

**Comment by ctron** [comment]
As @JimFuller-RedHat pointed out in the chat, this might be related to https://github.com/trustification/trustify/issues/552

**Comment by JimFuller-RedHat** [comment]
closing in prefer of https://github.com/trustification/trustify/issues/552
