### ISSUE TITLE
Time to materialise fully qualified purl ?

### ISSUE THREAD

**Issue by JimFuller-RedHat** [trustification/trustify#771]
Today for us to logically retrieve a purl of a component, we have to consult/join a few tables ... there is a **get_purl** fn that does this for us in upcoming PR ... though at scale (retrieving purls of a lot of components) is not very efficient.

We could add a column to **qualified_purl** which materialises constructed purl, though we would have to ensure that column is always updated whenever there are changes to base_purl or version_purl (via triggers, etc) ... perhaps its safe enough to always assume immutability here. 

By adding a column to existing table we can 'move over' incrementally ... though there are probably other approaches that are equally valid.

**Comment by ctron** [comment]
The qualified, versioned, and base purl entries should be considered immutable. Their primary key is a UUID v5 (digest) of the values. That's important to be able to know the key in advance.

At some point, I was thinking to just store the purl as a JSONB value. Like we do this with the qualifiers of the PURL. That can be indexed, and might just be good enough?!

**Comment by JimFuller-RedHat** [comment]
+1 to immutable though out of band maintenance might require us to mutate - we can be careful (with migraitons) if we ever need to do this.

JSONB or string is fine with me ...

**Comment by ctron** [comment]
The idea of JSONB for me was that we could still do a query like "give me all packages where purl->name = "foo""

**Comment by JimFuller-RedHat** [comment]
yes that works, and the cost of concat is tiny versus join ;)

**Comment by JimFuller-RedHat** [comment]
to add - this causes this warning - we perform this query loading sbom into analysis graph:

```
12024-09-12T15:46:24.269804Z  WARN sqlx::query: slow statement: execution time exceeded alert threshold summary="SELECT sbom.document_id, sbom.sbom_id, sbom.published::text, …" db.statement="\n\nSELECT\n  sbom.document_id,\n  sbom.sbom_id,\n  sbom.published :: text,\n  t1.node_id AS left_node_id,\n  get_purl(t1.qualified_purl_id) AS left_qualified_purl,\n  package_relates_to_package.relationship,\n  t2.node_id AS right_node_id,\n  get_purl(t2.qualified_purl_id) AS right_qualified_purl,\n  product.name AS product_name,\n  product_version.version AS product_version\nFROM\n  sbom\n  LEFT JOIN product_version ON sbom.sbom_id = product_version.sbom_id\n  LEFT JOIN product ON product_version.product_id = product.id\n  LEFT JOIN package_relates_to_package ON sbom.sbom_id = package_relates_to_package.sbom_id\n  LEFT JOIN sbom_package_purl_ref t1 ON sbom.sbom_id = t1.sbom_id\n  AND t1.node_id = package_relates_to_package.left_node_id\n  LEFT JOIN sbom_package_purl_ref t2 ON sbom.sbom_id = t2.sbom_id\n  AND t2.node_id = package_relates_to_package.right_node_id\nWHERE\n  package_relates_to_package.relationship IN (0, 8, 14)\n  AND sbom.sbom_id = '0191e6e9-f370-74f3-ae13-954772b5de18';\n" rows_affected=59375 rows_returned=59375 elapsed=2.464580393s elapsed_secs=2.464580393 slow_threshold=1s
```

**Comment by bobmcwhirter** [comment]
heya-- just to clarify, we'll keep some variant of `base_purl` yeah? Vuln/advisories are tracked as base+version_range.

**Comment by JimFuller-RedHat** [comment]
correct, old stuff is going to stay in place and we will incrementally remove (or switch queries) wherever it makes sense ... that approach is hopefully safer then a 'rip n replace'.
