### ISSUE TITLE
Don't forget that the initial CVE walker's git clone takes ~30 minutes

### ISSUE THREAD

**Issue by jcrossley3** [trustification/trustify#775]
The [CVE repo](https://github.com/CVEProject/cvelistV5) is over 3GB. Even a shallow clone is 2.7GB. 

The git cli takes almost 3 minutes to clone the full repo. The libgit2 rust crate takes almost 30 minutes. 
The git cli takes about 20s to create a shallow clone. The libgit2 rust crate takes about a minute.

Updates to the full clone are reasonably fast and it's efficient to determine which files need to be [re]ingested.

Updates to the shallow clone have [yet to be made to work](https://github.com/trustification/trustify/issues/764) successfully. 

Regardless, the "day 0" experience for new users is sucky. There is no visual indication whatsoever (in the UI or the server log) that the app is doing anything... for almost 30 minutes.

Consider this issue a placeholder for improving the "day 0" experience for enabling importers monitoring large git repos.

Possible alternatives:

- Figure out how to update a shallow clone with our existing `libgit2` crate.
- Shell out to the `git` CLI, which doesn't use `libgit2`, possibly enabling the deepening of an initial shallow clone in order to properly determine the changed files.
- Create a new shallow clone for every import cycle and calculate the digest of every file (~3GB worth of them) and query the db to determine whether they need to be ingested.

**Comment by ctron** [comment]
Maybe there's a forth option, speed up things with `libgit2`? 3 minutes don't feel bad (for a repository of this size).

**Comment by i386x** [comment]
@jcrossley3  Can you `strace` it? I mean `strace` both `git` cli and `trustd`/`libgit2` to see the difference?

**Comment by jcrossley3** [comment]
> @jcrossley3 Can you `strace` it? I mean `strace` both `git` cli and `trustd`/`libgit2` to see the difference?

Maybe? As I understand it, they're entirely different animals, and I lack the git foo to be able to map one's path to the other's.

**Comment by i386x** [comment]
> > @jcrossley3 Can you `strace` it? I mean `strace` both `git` cli and `trustd`/`libgit2` to see the difference?
> 
> Maybe? As I understand it, they're entirely different animals ...

I see. So `libgit2` is not built on the top of `git`, it is a (re)implementation of it. Then, like @helio-frota, I vote for shell out to the `git` cli.

**Comment by ctron** [comment]
That requires every system to run trustd, to also have a Git installation. That will be "fun" on Mac OS, Windows, and others …

**Comment by helio-frota** [comment]
>  That will be "fun" on Mac OS, Windows, and others

:man_facepalming: true thing

I remove my vote : )
