### ISSUE TITLE
Ensure we keep a limit

### ISSUE THREAD

**Issue by ctron** [trustification/trustify#778]
Taking a look at:

https://github.com/trustification/trustify/blob/54da44c176a22c1f931b2714c1816f915a42f0bc/modules/ingestor/src/service/format.rs#L61-L65

I am wondering if we enforce any kind of size limit? If we don't, we should.

**Comment by jcrossley3** [comment]
Not opposed, but we already enforce the limit on the actix handlers, which makes me wonder why the importers don't post their docs to the actix handlers? Doing so might facilitate distribution, too, right?
