### ISSUE TITLE
Getting information about an SBOM returns an excessive amount of data

### ISSUE THREAD

**Issue by ctron** [trustification/trustify#800]
The UI seems to call the "get SBOM (information)" endpoint (not download). That times out frequently, leading to missing information.

For one, I am not sure why that's a dedicated, additional call. If we're missing an API here, I think that should be raised as an issue @carlosthe19916 

Digging a bit deeper, I noticed that the backend returns an enormous amount of data:

* Request: `https://trustify.dentrassi.de/api/v1/sbom/urn:uuid:0191b3bd-07a2-7641-990e-11689b200af8`
* Response: `98.13 kB (79.03 MB size)`

I'll try to figure what data is being reported here.

**Comment by ctron** [comment]
It looks like as if most of the information is made up by advisories. I am not sure it makes sense stuffing that into the same request.

My proposal would be to create two endpoints:

* `http://locahost/api/v1/sbom/urn:uuid:0191b3bd-07a2-7641-990e-11689b200af8` reporting everything except the advisories section
* `http://locahost/api/v1/sbom/urn:uuid:0191b3bd-07a2-7641-990e-11689b200af8/advisories` reporting the advisories section only

cc @bobmcwhirter @carlosthe19916

**Comment by carlosthe19916** [comment]
I agree, we could avoid mixing things and separate them. My two cents:
- Yes, it is the `advisories` field what is the heaviest.
- A similar problem exists in the Vulnerability endpoint. Perhaps we could apply the same strategy suggested also in the other endpoints.

One option is to go for what @ctron suggested.
The other option is to use:

1. http://locahost/api/v1/sbom/urn:uuid:0191b3bd-07a2-7641-990e-11689b200af8 reporting everything except the advisories section
2. http://locahost/api/v1/advisory?sbom_id=urn:uuid:0191b3bd-07a2-7641-990e-11689b200af8 reporting the advisories section only - note that we are enhancing the already existing `advisory` endpoint without creating a new endpoint to the already existing list of endpoints. This way we could have a single point where to retrieve advisories and not multiple ones.

**Comment by ctron** [comment]
Ah, I wasn't aware of this. Yes, that makes sense. I'll take a look.

**Comment by ctron** [comment]
Ok, it looks like the information is actually different. So I'd to with the initial idea.
