### ISSUE TITLE
V2 CI/CD pipeline and deployment to Trustify Staging

### ISSUE THREAD

**Issue by PhilipCattanach** [trustification/trustify#804]
Create a new Trustify Staging environment on infrastructure paid for by Red Hat. 
Essentially a V2 equivalent of https://staging.trustification.dev/
Create the Trustify build pipeline so that every commit to the main branch triggers a new build and executes the integration tests. On a nightly basis the latest build must be automatically deployed to Trustify Staging.

**Comment by PhilipCattanach** [comment]
@jcrossley3 - Both Jens and Dejan help manage the costs of cloud based infrastructure. I think they were both involved in the set-up of the https://staging.trustification.dev/ and https://trustification.dev/ environments. Speaking to those guys would be where to start.

**Comment by jcrossley3** [comment]
@ctron @dejanb you've been summoned. help?

**Comment by jcrossley3** [comment]
Correct me if I'm wrong, but this issue seems to be a request to migrate https://trustify.dentrassi.de/ to https://staging.trustification.dev/ and since @ctron set the former up, I would be entirely relying on his expertise to close this issue.

**Comment by ctron** [comment]
I think it would be something new. `https://trustify.dentrassi.de/` is more like a personal instance, not using any OCP stuff.

So we'd need to come up with new Helm charts, or an operator, or some Ansible scripts to get there.

**Comment by jcrossley3** [comment]
Well, I'm personally clueless wrt all of those. :smile:

**Comment by carlosthe19916** [comment]
My two cents:
Whatever is the strategy used for deploying Trustify (as described in this gh issue) it would be great not to create an "independent way of deploying things just for this use case". E.g. for the old Trustification it seems we had a whole independent way of deploying it through https://github.com/trustification/trustification.rocks but as the time goes we stopped maintaining it in favor of the pipelines defined by Conflux and the official Helm charts we distribute as RHTPA.

So ideally , we should reuse whatever strategy that work on the long term (so we guarantee that we will always maintain it) without creating too much of an extra work.

**Comment by bobmcwhirter** [comment]
We have budget for environments on AWS.

I don't know that we necessarily need (at this point) OpenShift, since "deploy on RHEL" is also a goal.

I think order of operations is probably:

1. Get it building in Konflux.
2. Get each builds deployed ... somewhere easy and simple
3. No idea
4. Enjoy some cake
5. Figure out deployment into something less easy and simple, probably involving k8s.

**Comment by jcrossley3** [comment]
> 1. Get it building in Konflux.

I think this is done: https://console.redhat.com/application-pipeline/workspaces/trusted-content/applications/rhtpa

> 2. Get each builds deployed ... somewhere easy and simple

Can konflux do this?

> 3. No idea

Me either.

> 4. Enjoy some cake

Mmm.

> 5. Figure out deployment into something less easy and simple, probably involving k8s.

Why?

**Comment by bobmcwhirter** [comment]
Yah, I dunno if there's a "why" for 5. If we make it to step #2, we can re-evaluate beyond that.

I think @ctron was using ArgoCD for (2) (two) (II)

**Comment by helio-frota** [comment]
> Can konflux do this?

> No idea

+1 here

also that's not a "true" update -> deploy process if we need to manually update https://github.com/trustification/rhtpa fork repository 

* update trustify
* manually update rhtpa fork
* audomatic deploy the fork ?

**Comment by helio-frota** [comment]
in konlfux, the "release" is the "deployment"


> "A release object represents a deployed snapshot of your application components."


https://konflux-ci.dev/docs/advanced-how-tos/releasing/

**Comment by helio-frota** [comment]
and probably the `integration test` is this part https://konflux-ci.dev/docs/how-tos/testing/#integration-tests
