### ISSUE TITLE
Can the openapi.yaml file be created automatically by a gh action that is triggered by each commit?

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#807]
I might be wrong but it seems the openapi.yaml file is maintained manually but it should be automatically created or modified by each commit that arrives to the main branch or tag in which the gh actions is triggered.

As a bonus point: each time there is a change in the file openapi.yaml file then it would be nice to have a PR automatically created in the UI repository here https://github.com/trustification/trustify-ui/blob/main/client/openapi/trustd.yaml . The UI strongly depends on the openapi definition and as the main client of the backend it needs to be intermediately informed about changes in the openapi definition as soon as there is any. (this task can be done separately and if it is a complex task it can also be postponed  IMO)

**Comment by ctron** [comment]
Creating stuff automatically during github actions and committing it isn't a trivial thing. Commits created by github actions don't trigger builds. Merging stuff like that also isn't fun.

On the other hand @chirino created `cargo xtask precommit`, which does what is required. And we have a CI that reminds you of doing that.

I think that's way better than any complex CI.

**Comment by JimFuller-RedHat** [comment]
agree with @ctron - we have a good setup with `cargo xtask precomit` (which includes `cargo xtask openapi `which generates openapi) which gh actions takes advantage of today.

**Comment by carlosthe19916** [comment]
Are you guys saying that the `openapi.yaml` is already being generated automatically? If so, we can ignore my request :)
