### ISSUE TITLE
SPDX/SBOM and CSAF/VEX correlation

### ISSUE THREAD

**Issue by PhilipCattanach** [trustification/trustify#808]
For version 1 of RHTPA Marco Rizzi created a slice deck that describing proposals for the correlation logic.
[Proposal #2](https://docs.google.com/presentation/d/1KLP9cDWyWw-uNWgUinESeDwCnG_O5UpPKUVeRqedpl0/edit#slide=id.g24c439e1718_1_5) was approved and implemented. 
As the first step for implementing the correlation logic in version 2 we need a document that describes the process/algorithm.

**Comment by dejanb** [comment]
This issue is a documentation task for #853
