### ISSUE TITLE
Add API endpoint to interface with a Trustify tooled AI assistant.

### ISSUE THREAD

**Issue by chirino** [trustification/trustify#811]
The endpoints should provide a chat interface with an AI assistant that uses the Trustify database to respond to user questions.

**Comment by chirino** [comment]
This basically means figure out a good API that a web UI can use to do similar things to what was prototyped in this branch:
https://github.com/chirino/trustify/tree/ai

**Comment by chirino** [comment]
@carlosthe19916 hey do you want to help design the API?

**Comment by carlosthe19916** [comment]
@chirino I've been looking at some applications that use the "chat" way of interacting with AI. And almost all of them (including ChatGPT) use just a single REST endpoint with event streaming for sending the required text from the backend to the client.

Something like POST `/conversation`.

I am not sure how much of a complexity we might have but even for Chat GPT a single endpoint seemed to be enough. For starters, we you mentioned in the internal chat, having a blocking REST endpoints that gives back the whole response text would be enough. But as I mentioned I still need more exposure to this kind of APIs for better understanding.

**Comment by chirino** [comment]
Ok let's start simple and evolve as we go.

**Comment by jcrossley3** [comment]
Assuming fixed by #830
