### ISSUE TITLE
Rolling back last migration throws error from previous migration

### ISSUE THREAD

**Issue by JimFuller-RedHat** [trustification/trustify#839]
Developing a local migration for an upcoming PR I wanted to rollback ... using 

```
> sea-orm-cli migrate down
```

but I get an error in a previous migration
```
   --> migration/src/m0000543_create_license.rs:64:22
    |
64  |     let uuid = Uuid::new_v5(&NAMESPACE, name.to_lowercase().as_bytes());
    |                      ^^^^^^ function or associated item not found in `Uuid`
```

Not a blocker though we probably want to address this - alternately maybe when we roll up all these migrations when we hit a 1.0.0 this just _'goes away'_.

**Comment by ctron** [comment]
Hm, interesting. I though we'd had a test for up/down migration.

**Comment by ctron** [comment]
Ah, I guess it's a missing feature flag. That might happen, as features are additive. Probably a simple fix.

**Comment by ctron** [comment]
Yes, that was easy. We do enable the `uuid` feature of seaorm. However, that enabled the `uuid` crate without any features. So instead, we need to directly use `uuid`, and enable required features.
