### ISSUE TITLE
SBOM List - V1 Parity - SORTING

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#886]
![Screenshot from 2024-10-04 10-24-17](https://github.com/user-attachments/assets/6768d161-2afe-4191-8e09-47e5e645e531)

Hi Guys, for achieving V1 parity in terms the SBOM List page we need to be as close as possible to the V1 UI.

In terms of Sorting, V1 UI didn't include many Sort columns because of the limitations in the old Index architecture right? Those limitations were somehow addressed in the new version I think. @mid998 mentioned she would like to have Sorting in ALL columns. So Here are the following columns we need Sorting. Let's define how to achieve it.

- **Name**.- V1 does not have this sorting but V2 should have it, unless there is a reason not to do it.
- **Version**.- V1 does not have this sorting. Are we going to do it in V2? If YES, what is the REST query for doing it? If NO, then let's make it clear we won't do it.
- **Supplier**.- V1 does not have this sorting. Are we going to do it in V2? If YES, what is the REST query for doing it? If NO, then let's make it clear we won't do it.
- **Published**.- V1 and V2 already have this one so nothing to do.
- **Packages**.- This column represents the count of packages for each SBOM. How to sort the SBOM list by Count of Packages? Are we going to implement this? If Yes or No, let's document it.
- **Vulnerabilities**.- At the moment I am not sure how that column will look like, so we can postpone the decision of this column for later. But @mid998 mentioned that it would be nice to answer "Which are the top SBOM with Highest number of Vulnerabilities". Questions like that are done with sorting. We can brainstorm how to achieve it.

## Sort by NAME
If I hit

```
/api/v1/sbom?limit=10&offset=0&sort=name:asc
```

The server returns

```json
{
    "error": "Query error",
    "message": "query syntax error: Invalid sort field: 'name'"
}
```

This is a bug right? Can we fix it?

## Sort by VERSION
Can we do this with the current models?
```
/api/v1/sbom?limit=10&offset=0&sort=described_by.version:asc
```
Would the previous request work? 
Let's decide if we can do this sorting or no.

## Sort by SUPPLIER
If I hit
```
/api/v1/sbom?limit=10&offset=0&sort=authors:asc
```
it works, surprisingly (it returns data without throwing errors in the backend). As a single SBOM can have multiple authors, I don't know if the response of the server is accurate. Is the previous request correct and should be implemented in the UI?

## Sort by PUBLISHED
V1 + V2 fully implemented this so nothing to do

## Sort by PACKAGES
The UI can render the count of packages but cannot sort the SBOM List by Count of packages as the current rest endpoint does not support it yet. Would it be possible to achieve it? Let's discuss it

## Sort by VULNERABILITIES
This will be a challenge even from the design point of view. So any brainstorm would be welcome .

**Comment by carlosthe19916** [comment]
This issue will help to define the UI side implementation and documented here https://github.com/trustification/trustify-ui/issues/155

**Comment by jcrossley3** [comment]
This will require some investigation, but should be doable. Need to come to terms with the CI pipeline stuff first.

**Comment by jcrossley3** [comment]
Good to know, because I'm finding some of them more difficult than others. I'll try to come up with a list, but I'd like to first convince myself the difficult ones aren't impossible, so doing a little exploratory surgery atm.

**Comment by jcrossley3** [comment]
I closed this because we have the v1 parity and I added the `name` field. Let's open separate issues for any extra we need as we find them.
