### ISSUE TITLE
Package List - V1 Parity - SORTING

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#888]
![image](https://github.com/user-attachments/assets/77ee1abd-024c-42e5-bab4-8d185573b88f)

V1 parity work is being done. I'd like us to agree on which columns the UI will be able to sort and how. If possible be able to sort by all columns the table has. Otherwise, make conscious decisions about why not.

V1 does not have a single column Sort. We didn't do Sorting in v1, I believe due to a design that limited us to do such thing but those limitations are solved now I think right?.

- **Sort by Name**: Which is the REST query to achieve it?
- **Sort by Version**: Which is the REST query to achieve it?
- **Sort by Type**: Which is the REST query to achieve it?
- **Sort by Vulnerabilities**: this column will render the total the count of vulnerabilities affecting the package. This might need a deeper discussion (we there are multiple advisories for the same package) but a brainstorm would be welcome.
- **Sort by SBOMs**: this column will render the total count of SBOMs that contain the package. I believe we can not do that at the moment, then let's decide whether or not we are able to do it.

**Comment by carlosthe19916** [comment]
This issue will help the completion of the UI side work at https://github.com/trustification/trustify-ui/issues/170

**Comment by jcrossley3** [comment]
@carlosthe19916 I closed this, but you still can't sort on the `qualifiers` and `vulnerabilities` columns. It's a more complicated change that I'd prefer to track in a separate issue, if you need it.

**Comment by carlosthe19916** [comment]
I agree. I don't think sort by "qualifiers" is relevant. Order by "vulnerabilities" might be more important, but for not we already covered V1 parity so I don't think we need to do more on this regard at least until the next release
