### ISSUE TITLE
Package List - V1 Parity - SBOM COUNT

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#889]
![Screenshot from 2024-10-04 12-46-50](https://github.com/user-attachments/assets/d2ce3a1e-1050-4050-a281-8acd5a91d9c5)

The image above (the red circle) should be populated with the total count of SBOM that each package has.

The only potential REST endpoint for getting the TOTAL is:
```
/api/v1/sbom/by-package?id={id}&limit=10&offset=0
```

### Problem
- The rest endpoint above requires the client to set a `limit`.  What value should I set to `limit`? Also setting no limits would have any performance penalties?
- The UI only needs the total count without the whole list of SBOMs. How can extract only the COUNT? fetching thousand of SBOM's data when the only data required is the COUNT doesn't seem reasonable

**Comment by ctron** [comment]
You can set the limit to 1. You'll still get the total number of entries.

The burden is actually not to fetch that one sbom, but to count all others. If anything, then removing the count would make sense from a performance perspective.

I agree that a single call of "give me the counts for the following packages" would make sense for this.

**Comment by ctron** [comment]
I any case, I think a dedicated call for this makes sense. Single call, array in, array out. But it shouldn't be a blocker.
