### ISSUE TITLE
Latest release deployment is broken after OCP changes

### ISSUE THREAD

**Issue by jcrossley3** [trustification/trustify#928]
I don't know for sure if @ctron 's recent configuration changes to our OCP cluster are the cause of the error, but the `deploy` job in the `latest-release` workflow [hasn't succeeded ever since](https://github.com/trustification/trustify/actions/runs/11364305072). It fails with the following error:
```
+ operator-sdk run bundle ghcr.io/trustification/trustify-operator-bundle:latest --namespace trustify-latest --timeout 15m
time="2024-10-17T10:31:35Z" level=info msg="Creating a File-Based Catalog of the bundle \"ghcr.io/trustification/trustify-operator-bundle:latest\""
time="2024-10-17T10:31:35Z" level=info msg="Generated a valid File-Based Catalog"
time="2024-10-17T10:31:39Z" level=info msg="Created registry pod: ghcr-io-trustification-trustify-operator-bundle-latest"
time="2024-10-17T10:31:39Z" level=info msg="Created CatalogSource: trustify-operator-catalog"
time="2024-10-17T10:31:39Z" level=info msg="OperatorGroup \"operator-sdk-og\" created"
time="2024-10-17T10:31:39Z" level=info msg="Created Subscription: trustify-operator-v1-0-0-snapshot-sub"
time="2024-10-17T10:46:27Z" level=fatal msg="Failed to run bundle: install plan is not available for the subscription trustify-operator-v1-0-0-snapshot-sub: Get \"[https://api.cluster.trustification.rocks:6443/apis/operators.coreos.com/v1alpha1/namespaces/trustify-latest/subscriptions/trustify-operator-v1-0-0-snapshot-sub\](https://api.cluster.trustification.rocks:6443/apis/operators.coreos.com/v1alpha1/namespaces/trustify-latest/subscriptions/trustify-operator-v1-0-0-snapshot-sub/)": context deadline exceeded\n"
```
I [tried updating to the latest operator-sdk release](https://github.com/trustification/trustify-operator/commit/93ea922b9d8d9f0c1f457604254edd126ddce518), but it didn't help.

I'm hoping @carlosthe19916 might offer some guidance on how to diagnose the problem.

**Comment by carlosthe19916** [comment]
@jcrossley3 I'll investigate tomorrow. Thanks for sharing the log. I'll see what changed recently for it to fail now

**Comment by ctron** [comment]
The cluster was converted into a multi-arch cluster. I am not sure what that means internally. Some nodes are now arm64 nodes. There's some information about multi-arch clusters here: https://docs.openshift.com/container-platform/4.16/post_installation_configuration/configuring-multi-arch-compute-machines/multi-architecture-compute-managing.html

For trustification (v1) I had to amend the Helm charts in a way that they only deploy pods on amd64, as we don't build and publish multi-arch images for v1.

**Comment by jcrossley3** [comment]
Is it easy enough to revert the multi-arch conversion? If the deploy job then works, at least we could confirm the correlation.

**Comment by ctron** [comment]
IIRC it was impossible.

**Comment by ctron** [comment]
Yea, not possible:

> Migration from a multi-architecture payload to a single-architecture payload is not supported. Once a cluster has transitioned to using a multi-architecture payload, it can no longer accept a single-architecture update payload.

**Comment by jcrossley3** [comment]
I'd love to know how you figured that out, but I'm afraid I may lack the expertise required to understand it.

**Comment by carlosthe19916** [comment]
> I'd love to know how you figured that out, but I'm afraid I may lack the expertise required to understand it.

I think it was just being lucky. As soon as I started reading this issue today, @ctron already mentioned the "multi-arch" change in the OCP cluster (which to me would be almost impossible to track as I know almost nothing about that OCP instance).

**Comment by jcrossley3** [comment]
I think you're being humble, but as they say in the casino, luck counts!
