### ISSUE TITLE
Backend API changes required to support TC-1130

### ISSUE THREAD

**Issue by jcrossley3** [trustification/trustify#945]
https://issues.redhat.com/browse/TC-1130

**Comment by carlosthe19916** [comment]
@jcrossley3 I think I created a duplicate of your issue and I've just realized. Here is the issue I created explaining some things https://github.com/trustification/trustify/issues/952

**Comment by jcrossley3** [comment]
Cool. I just wanted the jira link somewhere. I'll close this and add it over there.
