### ISSUE TITLE
SBOM Details - Info Tab

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#949]
On the left side of the image below we see the V1 UI and in the right side we have V2 UI (Trustify)

- We need to expose through the REST endpoints all the fields that the V1 used to render. 

![image](https://github.com/user-attachments/assets/8e58e3d4-6b14-4585-844a-09ebf002e4f1)

**Comment by ctron** [comment]
I think it would make sense to let us know which endpoint you're calling and which result you get. I see information lacking in the UI, but I also see that some of this information is available on the API.

**Comment by ctron** [comment]
Ok, the please use:

* `document_id` as Namespace
* `described_by` / `purl` and `cpe` as the external references

I'd drop the "SPDX version" and "license list version", as they don't really make sense.

I'll add:

* Size
* Data license
