### ISSUE TITLE
SBOM Details page - Vulnerabilities Tab - Updated column

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#950]
In V1 the vulnerabilities tab of the SBOM details page lists a set of vulnerabilities that affect the current SBOM.

In V1, each vulnerability has an "Updated" column. In V2 I do not see any "updated" field being exposed for Vulnerabilities. Could you tell me where to find it. Otherwise we might need to implement it.

![Screenshot From 2024-10-30 16-13-29](https://github.com/user-attachments/assets/8a275137-390a-4409-b82f-03f6dbd34537)

**Comment by jcrossley3** [comment]
Probably `modified`, right?

**Comment by carlosthe19916** [comment]
Got it! good to know The V1 `Updated` column is the `modified` field from a Vulnerability. I'll apply it!

**Comment by carlosthe19916** [comment]
Closing this issue as it has been solved.
