### ISSUE TITLE
Package List - Filtering

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#951]
This is how it looks V1 Package List page:

![Screenshot From 2024-10-30 16-25-07](https://github.com/user-attachments/assets/c4b2a990-8bd4-42e1-a1c9-01a635e0dea6)

- In v2 UI I am using the endpoint `/api/v1/purl` for populating the table in the UI.

There are 2 main filters I need to implement in V2.

- Type Filter: 
  - I am currently using `q=type=maven|rpm|npm|oci` and it works! So I guess there is nothing to do on that.
- Architecture Filter:
  - I was not able to make it work with `q=arch=x86_64|aarch64|ppc64le|s390x|noarch` so would you advice me how to filter by Architecture?

**Comment by jcrossley3** [comment]
>   * I am currently using `q=type=maven|rpm|npm|oci` and it works! So I guess there is nothing to do on that.

Yay!

>   * I was not able to make it work with `q=arch=x86_64|aarch64|ppc64le|s390x|noarch` so would you advice me how to filter by Architecture?

Boo! I'll investigate.

**Comment by jcrossley3** [comment]
@carlosthe19916 when #1073 merges, this should work as you expect: `q=type=maven|rpm&arch=x86_64|noarch`

Regarding `type`, keep in mind that `type=maven` (not `pom`) for the following purl: `pkg:maven/org.apache.xmlgraphics/batik-anim@1.9.1?type=pom`

If we need to query `type` as a purl _qualifier_, we'll need to introduce a non-conflicting name for the purl's type, e.g. we use `ty` in the db.

Speaking of qualifiers, these are the only ones we currently support: `arch`, `distro`, and `repository_url`. But it's trivial to add more.

**Comment by carlosthe19916** [comment]
Awesome! Thanks @jcrossley3 I tested your PR and it worked as a charm. 
- The UI already have set up the Filtering
- https://github.com/trustification/trustify-ui/pull/291 is for adding sorting. Which I tested and also worked

We can close this issue as completed I think
