### ISSUE TITLE
How to render data for V1 parity

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#953]
cc: @mid998 @PhilipCattanach 

- It has been decided that for having parity we will only ingest OSV + CSAF data; every other source of data will be disabled and will only be available after "V2"
- Currently the models can tell us that certain vulnerabilities can have multiple statuses like `fixed | note_affected | known_not_affected | affected`. My understanding is that we will only take into account "affected" statuses as in V1 we only show vulnerabilities that affect a package or SBOM.

I'd like to know exactly which steps I need to follow to see Relationships in the System: SBOM - Vulnerabilities / Package - Vulnerabilities, etc.

I expect the answer to be something like: "enable X,Y,Z importers". But I'd like the steps officially documented and give zero chance to misinterpretation.

The reason is that it is getting difficult to get "affected" packages with only the OSV + CSAF importers. Of course there is a high chance that I am doing something wrong but having an official statement about it will help not just me but anyone who tries Trustify.

**Comment by ctron** [comment]
If we're not going to ingest CVE data, we might lack a bunch of information that we do have in V1.

**Comment by ctron** [comment]
> What would be the recommended set of sources/data to import in order to have the same results as in V1?

Same as v1: SBOMs from Red Hat, Advisories from Red Hat, CVEs from https://github.com/CVEProject/cvelistV5

**Comment by carlosthe19916** [comment]
Closing this PR. As the right set of importers will be defined by the Helm chart
