### ISSUE TITLE
Importer: Only CSAF importers seem to have the "progress" information

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#962]
When I hit `/api/v1/importer` I get the list of all importers. If by any chance I have a CSAF importer running I get a response similar to:

```json
[
    {
        "name": "redhat-csaf",
        "configuration": {
            "csaf": {
                "disabled": false,
                "period": "5m",
                "description": "All Red Hat CSAF data",
                "source": "redhat.com",
                "v3Signatures": true,
                "fetchRetries": 50
            }
        },
        "state": "running",
        "lastChange": "2024-11-01T14:13:24.523127Z",
        "lastRun": "2024-11-01T14:00:44.184209Z",
        "lastError": "Visitor error: operation canceled",
        "progress": {
            "current": 1,
            "total": 17652,
            "percent": 0.000056650806,
            "rate": 0.20685275,
            "estimated_seconds_remaining": 85331,
            "estimated_completion": "2024-11-02T13:55:40.357483824Z"
        }
    },   
]
```

The JSON above has a field `progress` which helps to track the progress of the task.

The problem is that the CSAF importer is the only one that generates the `progress` fields. None of the other importers generate the `progress` field.

This is an example of how it looks when I hit `/api/v1/importer` and I have a CVE importer running:

```json
[
    {
        "name": "cve-from-2024",
        "configuration": {
            "cve": {
                "disabled": false,
                "period": "5m",
                "description": "CVE List V5 (starting 2024)",
                "source": "https://github.com/CVEProject/cvelistV5",
                "startYear": 2024
            }
        },
        "state": "running",
        "lastChange": "2024-11-01T14:16:45.182996Z"
    }
]
```

You can see that the importer has state `running` and yet the `progress` field is not populated in the backend response. 
There must be consistency in the backend response, either all Importers have the `progress` field or none of them.

**Comment by ctron** [comment]
> There must be consistency in the backend response, either all Importers have the `progress` field or none of them.

Not sure where that requirement comes from.

**Comment by ctron** [comment]
I think I noticed was that the progress struct doesn't use `camelCase`, I'll change that.

**Comment by carlosthe19916** [comment]
Closing this issue. If further changes are requested I'll open a new issue
