### ISSUE TITLE
Advisory "revision" date does not exist

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#967]
The V1 UI contains "Revision" date for Advisories. Could we also add that property for advisories? `/api/v1/advisory`

![Screenshot From 2024-11-05 13-18-00_1](https://github.com/user-attachments/assets/da00067a-6d93-4f8f-8b8d-91510a44a2d4)

**Comment by ctron** [comment]
I'd recommend using the `modified` field.

**Comment by carlosthe19916** [comment]
> I'd recommend using the `modified` field.

Thanks. I'll close this ticket as there is nothing to implement. There was another issue related to this one that I will also close https://github.com/trustification/trustify/issues/968.
