### ISSUE TITLE
Curious unused code snippet relating to querying jsonb fields

### ISSUE THREAD

**Issue by jcrossley3** [trustification/trustify#972]
@JimFuller-RedHat I'm thinking this is related to something I'm working on, #888, and I'm curious why it's not in a comment. :smile: 
 
https://github.com/trustification/trustify/blob/68d08bc52e6e65ac8d352ad524904df7a20d2cf8/modules/fundamental/src/purl/service/mod.rs#L336-L343

**Comment by JimFuller-RedHat** [comment]
generally we still have work to do to port over calls with joins across 3 tables to just refer to qualified_purl purl column ... and yes you are right - that condition can now be removed - I will do that as part of PR I am cooking up in analysis graph area (adding cpe to each node).
