### ISSUE TITLE
CVEs Related Advisories missing props for v1 parity

### ISSUE THREAD

**Issue by kahboom** [trustification/trustify#976]
In v1 CVE detail page you have the following properties visible for its related advisories, which are not available now:

- `Revision`
- `Vulnerabilities`
- No `aggregate severity` showing up in column value despite `severity` existing? This might just be a "not enough data" issue on my part

See also [this](https://docs.google.com/spreadsheets/d/1mhBd3-UYvSANIXwRPDrCdGplN7cq5rQPJhIywo5mcDY/edit?gid=1088076328#gid=1088076328) spreadsheet for a complete list of properties missing in the current version of the UI.

![Screenshot 2024-11-06 at 2 04 54 PM copy](https://github.com/user-attachments/assets/31672464-40f7-46cb-a77f-21a71cbaa223)

**Comment by ctron** [comment]
I think that "Aggregated severity" is already available:

![image](https://github.com/user-attachments/assets/42c0bac5-be99-4baf-9fba-80709e4f6757)

It's just the wrong column header. Because that's a severity, not a score.

**Comment by ctron** [comment]
Taking a look at the "revision", I think it's just the advisory's date. So you should be able to use `modified`.
