### ISSUE TITLE
Loading SBOMs fails with 500

### ISSUE THREAD

**Issue by ctron** [trustification/trustify#984]
Loading of SBOMs fails. In the logs I can see:

```
2024-11-08T11:26:25.268506Z ERROR ThreadId(09) trustify_module_fundamental::error: Type Error: A null value was encountered while decoding "A_data_licenses"    
```

**Comment by helio-frota** [comment]
`rm -Rf .trustify` ?

**Comment by JimFuller-RedHat** [comment]
example sbom ?

**Comment by ctron** [comment]
Trying to figure it all out. It's using an external database, so I doubt `.trustify` is an issue.

**Comment by ctron** [comment]
I think this came in through 1164a4fd5a2b678950a952854c38591b62fa6435

**Comment by jcrossley3** [comment]
I saw this, and blew away `.trustify/` and haven't seen it since, which to me implied some migration didn't change the data it should have. So something about the data in your external db is triggering it somehow?

**Comment by ctron** [comment]
> I saw this, and blew away `.trustify/` and haven't seen it since, which to me implied some migration didn't change the data it should have. So something about the data in your external db is triggering it somehow?

Right, that would work. As you nuked the data. I'd say the migration was buggy. #985 fixes that.
